(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(){function Y(b){function a(f,a){Object.defineProperty(f,"innerHTML",{enumerable:a.enumerable,configurable:!0,get:a.get,set:function(f){var e=this,d=void 0;k(this)&&(d=[],q(this,function(b){b!==e&&d.push(b)}));a.set.call(this,f);if(d)for(var c=0;c<d.length;c++){var g=d[c];1===g.__CE_state&&b.disconnectedCallback(g)}this.ownerDocument.__CE_hasRegistry?b.patchAndUpgradeTree(this):b.patchTree(this);return f}})}function d(a,e){m(a,"insertAdjacentElement",function(a,f){var d=k(f);
a=e.call(this,a,f);d&&b.disconnectTree(f);k(a)&&b.connectTree(f);return a})}I?m(Element.prototype,"attachShadow",function(b){return this.__CE_shadowRoot=b=I.call(this,b)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(t&&t.get)a(Element.prototype,t);else if(A&&A.get)a(HTMLElement.prototype,A);else{var c=B.call(document,"div");b.addPatch(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return J.call(this,!0).innerHTML},set:function(b){var a="template"===this.localName?
this.content:this;for(c.innerHTML=b;0<a.childNodes.length;)C.call(a,a.childNodes[0]);for(;0<c.childNodes.length;)v.call(a,c.childNodes[0])}})})}m(Element.prototype,"setAttribute",function(a,d){if(1!==this.__CE_state)return K.call(this,a,d);var f=D.call(this,a);K.call(this,a,d);d=D.call(this,a);b.attributeChangedCallback(this,a,f,d,null)});m(Element.prototype,"setAttributeNS",function(a,d,c){if(1!==this.__CE_state)return L.call(this,a,d,c);var f=w.call(this,a,d);L.call(this,a,d,c);c=w.call(this,a,
d);b.attributeChangedCallback(this,d,f,c,a)});m(Element.prototype,"removeAttribute",function(a){if(1!==this.__CE_state)return M.call(this,a);var d=D.call(this,a);M.call(this,a);null!==d&&b.attributeChangedCallback(this,a,d,null,null)});m(Element.prototype,"removeAttributeNS",function(a,d){if(1!==this.__CE_state)return N.call(this,a,d);var f=w.call(this,a,d);N.call(this,a,d);var c=w.call(this,a,d);f!==c&&b.attributeChangedCallback(this,d,f,c,a)});O?d(HTMLElement.prototype,O):P?d(Element.prototype,
P):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");Q(b,Element.prototype,{prepend:Z,append:aa});ba(b,Element.prototype,{before:ca,after:da,replaceWith:ea,remove:fa})}function ba(b,a,d){a.before=function(a){for(var f=[],c=0;c<arguments.length;++c)f[c-0]=arguments[c];c=f.filter(function(b){return b instanceof Node&&k(b)});d.before.apply(this,f);for(var g=0;g<c.length;g++)b.disconnectTree(c[g]);if(k(this))for(c=0;c<f.length;c++)g=f[c],g instanceof Element&&b.connectTree(g)};
a.after=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];e=c.filter(function(b){return b instanceof Node&&k(b)});d.after.apply(this,c);for(var g=0;g<e.length;g++)b.disconnectTree(e[g]);if(k(this))for(e=0;e<c.length;e++)g=c[e],g instanceof Element&&b.connectTree(g)};a.replaceWith=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];e=c.filter(function(b){return b instanceof Node&&k(b)});var g=k(this);d.replaceWith.apply(this,c);for(var r=0;r<e.length;r++)b.disconnectTree(e[r]);
if(g)for(b.disconnectTree(this),e=0;e<c.length;e++)g=c[e],g instanceof Element&&b.connectTree(g)};a.remove=function(){var a=k(this);d.remove.call(this);a&&b.disconnectTree(this)}}function ha(b){function a(a,c){Object.defineProperty(a,"textContent",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)c.set.call(this,a);else{var d=void 0;if(this.firstChild){var f=this.childNodes,r=f.length;if(0<r&&k(this)){d=Array(r);for(var h=0;h<r;h++)d[h]=f[h]}}c.set.call(this,
a);if(d)for(a=0;a<d.length;a++)b.disconnectTree(d[a])}}})}m(Node.prototype,"insertBefore",function(a,c){if(a instanceof DocumentFragment){var d=Array.prototype.slice.apply(a.childNodes);a=R.call(this,a,c);if(k(this))for(c=0;c<d.length;c++)b.connectTree(d[c]);return a}d=k(a);c=R.call(this,a,c);d&&b.disconnectTree(a);k(this)&&b.connectTree(a);return c});m(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=v.call(this,a);if(k(this))for(var d=
0;d<c.length;d++)b.connectTree(c[d]);return a}c=k(a);d=v.call(this,a);c&&b.disconnectTree(a);k(this)&&b.connectTree(a);return d});m(Node.prototype,"cloneNode",function(a){a=J.call(this,a);this.ownerDocument.__CE_hasRegistry?b.patchAndUpgradeTree(a):b.patchTree(a);return a});m(Node.prototype,"removeChild",function(a){var c=k(a),d=C.call(this,a);c&&b.disconnectTree(a);return d});m(Node.prototype,"replaceChild",function(a,c){if(a instanceof DocumentFragment){var d=Array.prototype.slice.apply(a.childNodes);
a=S.call(this,a,c);if(k(this))for(b.disconnectTree(c),c=0;c<d.length;c++)b.connectTree(d[c]);return a}d=k(a);var e=S.call(this,a,c),g=k(this);g&&b.disconnectTree(c);d&&b.disconnectTree(a);g&&b.connectTree(a);return e});E&&E.get?a(Node.prototype,E):b.addPatch(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)C.call(this,this.firstChild);v.call(this,
document.createTextNode(a))}})})}function ia(b){m(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var d=b.localNameToDefinition(a);if(d)return new d.constructor}a=B.call(this,a);b.patch(a);return a});m(Document.prototype,"importNode",function(a,d){a=ja.call(this,a,d);this.__CE_hasRegistry?b.patchAndUpgradeTree(a):b.patchTree(a);return a});m(Document.prototype,"createElementNS",function(a,d){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var c=b.localNameToDefinition(d);
if(c)return new c.constructor}a=ka.call(this,a,d);b.patch(a);return a});Q(b,Document.prototype,{prepend:la,append:ma})}function Q(b,a,d){a.prepend=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];e=c.filter(function(a){return a instanceof Node&&k(a)});d.prepend.apply(this,c);for(var g=0;g<e.length;g++)b.disconnectTree(e[g]);if(k(this))for(e=0;e<c.length;e++)g=c[e],g instanceof Element&&b.connectTree(g)};a.append=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];
e=c.filter(function(a){return a instanceof Node&&k(a)});d.append.apply(this,c);for(var g=0;g<e.length;g++)b.disconnectTree(e[g]);if(k(this))for(e=0;e<c.length;e++)g=c[e],g instanceof Element&&b.connectTree(g)}}function na(b){window.HTMLElement=function(){function a(){var a=this.constructor,c=b.constructorToDefinition(a);if(!c)throw Error("The custom element being constructed was not registered with `customElements`.");var f=c.constructionStack;if(0===f.length)return f=B.call(document,c.localName),
Object.setPrototypeOf(f,a.prototype),f.__CE_state=1,f.__CE_definition=c,b.patch(f),f;c=f.length-1;var e=f[c];if(e===T)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");f[c]=T;Object.setPrototypeOf(e,a.prototype);b.patch(e);return e}a.prototype=oa.prototype;return a}()}function l(b){this._elementDefinitionIsRunning=!1;this._internals=b;this._whenDefinedDeferred=new Map;this._flushCallback=function(a){return a()};this._flushPending=
!1;this._unflushedLocalNames=[];this._documentConstructionObserver=new F(b,document)}function G(){var b=this;this._resolve=this._value=void 0;this._promise=new Promise(function(a){b._resolve=a;b._value&&a(b._value)})}function F(b,a){this._internals=b;this._document=a;this._observer=void 0;this._internals.patchAndUpgradeTree(this._document);"loading"===this._document.readyState&&(this._observer=new MutationObserver(this._handleMutations.bind(this)),this._observer.observe(this._document,{childList:!0,
subtree:!0}))}function n(){this._localNameToDefinition=new Map;this._constructorToDefinition=new Map;this._patches=[];this._hasPatches=!1}function U(b){var a=pa.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function k(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}function H(b,a){for(;a&&
a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}function q(b,a,d){d=void 0===d?new Set:d;for(var c=b;c;){if(c.nodeType===Node.ELEMENT_NODE){var f=c;a(f);var e=f.localName;if("link"===e&&"import"===f.getAttribute("rel")){c=f.import;if(c instanceof Node&&!d.has(c))for(d.add(c),c=c.firstChild;c;c=c.nextSibling)q(c,a,d);c=H(b,f);continue}else if("template"===e){c=H(b,f);continue}if(f=f.__CE_shadowRoot)for(f=f.firstChild;f;f=f.nextSibling)q(f,a,d)}c=c.firstChild?c.firstChild:H(b,
c)}}function m(b,a,d){b[a]=d}(function(b){function a(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function d(a){if(m)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!k(b)&&(b=b.parentNode););a.__importDoc=b}return b}function c(a){var b=
document.querySelectorAll("link[rel=import]:not(import-dependency)"),c=b.length;c?l(b,function(b){return g(b,function(){0===--c&&a()})}):a()}function f(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function e(a){f(function(){return c(function(){return a&&a()})})}function g(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=
!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);t&&"style"===a.localName||a.addEventListener("error",c)}}function k(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function h(){var a=this;this.documents={};this.inflight=0;this.dynamicImportsMO=new MutationObserver(function(b){return a.handleMutations(b)});this.dynamicImportsMO.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}
function l(a,b,c){var d=a?a.length:0,qa=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=qa)b(a[c],c)}var m="import"in document.createElement("link"),n=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return n||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var q=/(^\/)|(^#)|(^[\w-\d]*:)/,v=/(url\()([^)]*)(\))/g,w=/(@import[\s]+(?!url\())([^;]*)(;)/g,x=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,p={fixUrls:function(a,
b){a.href&&a.setAttribute("href",p.replaceAttrUrl(a.getAttribute("href"),b));a.src&&a.setAttribute("src",p.replaceAttrUrl(a.getAttribute("src"),b));if("style"===a.localName){var c=p.replaceUrls(a.textContent,b,v);a.textContent=p.replaceUrls(c,b,w)}},replaceUrls:function(a,b,c){return a.replace(c,function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=p.resolveUrl(a,b));return c+"'"+a+"'"+e})},replaceAttrUrl:function(a,b){return a&&q.test(a)?a:p.resolveUrl(a,b)},resolveUrl:function(a,b){if(void 0===p.__workingURL){p.__workingURL=
!1;try{var c=new URL("b","http://a");c.pathname="c%20d";p.__workingURL="http://a/c%20d"===c.href}catch(sa){}}if(p.__workingURL)return(new URL(a,b)).href;c=p.__tempDoc;c||(c=document.implementation.createHTMLDocument("temp"),p.__tempDoc=c,c.__base=c.createElement("base"),c.head.appendChild(c.__base),c.__anchor=c.createElement("a"));c.__base.href=b;c.__anchor.href=a;return c.__anchor.href||a}},u={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?
atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,u.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},t=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);h.prototype.loadImports=
function(a){var b=this;a=a.querySelectorAll("link[rel=import]");l(a,function(a){return b.loadImport(a)})};h.prototype.loadImport=function(a){var b=this,c=a.href;if(void 0!==this.documents[c]){var d=this.documents[c];d&&d.__loaded&&(a.import=d,this.fireEventIfNeeded(a))}else this.inflight++,this.documents[c]="pending",u.load(c,function(a,d){a=b.makeDocument(a,d||c);b.documents[c]=a;b.inflight--;b.loadImports(a);b.processImportsIfLoadingDone()},function(){b.documents[c]=null;b.inflight--;b.processImportsIfLoadingDone()})};
h.prototype.makeDocument=function(a,b){if(!a)return document.createDocumentFragment();t&&(a=a.replace(x,function(a,b,c){return-1===a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content;else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=p.replaceAttrUrl(c.getAttribute("href"),b),c.removeAttribute("href");c=a.querySelectorAll('link[rel=import], link[rel=stylesheet][href][type=import-disable],\n    style:not([type]), link[rel=stylesheet][href]:not([type]),\n    script:not([type]), script[type="application/javascript"],\n    script[type="text/javascript"]');
var d=0;l(c,function(a){g(a);p.fixUrls(a,b);a.setAttribute("import-dependency","");"script"===a.localName&&!a.src&&a.textContent&&(a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n"))),a.textContent="",d++)});return a};h.prototype.processImportsIfLoadingDone=function(){var a=this;if(!this.inflight){this.dynamicImportsMO.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.loadImports(document),a.inflight||
(a.dynamicImportsMO.observe(document.head,{childList:!0,subtree:!0}),a.fireEvents()))};this.waitForStyles(function(){c=!0;d()});this.runScripts(function(){b=!0;d()})}};h.prototype.flatten=function(a){var b=this;a=a.querySelectorAll("link[rel=import]");l(a,function(a){var c=b.documents[a.href];(a.import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.documents[a.href]=a,a.readyState="loading",a.import=a,b.flatten(c),a.appendChild(c))})};h.prototype.runScripts=function(a){function b(e){if(e<d){var f=
c[e],h=document.createElement("script");f.removeAttribute("import-dependency");l(f.attributes,function(a){return h.setAttribute(a.name,a.value)});n=h;f.parentNode.replaceChild(h,f);g(h,function(){n=null;b(e+1)})}else a()}var c=document.querySelectorAll("script[import-dependency]"),d=c.length;b(0)};h.prototype.waitForStyles=function(a){var b=document.querySelectorAll("style[import-dependency],\n    link[rel=stylesheet][import-dependency]"),c=b.length;if(c){var e=t&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");
l(b,function(b){g(b,function(){b.removeAttribute("import-dependency");0===--c&&a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=d(b);f&&d(f);)f=d(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};h.prototype.fireEvents=function(){var a=this,b=document.querySelectorAll("link[rel=import]");
l(b,function(b){return a.fireEventIfNeeded(b)},!0)};h.prototype.fireEventIfNeeded=function(b){b.__loaded||(b.__loaded=!0,b.import&&(b.import.readyState="complete"),b.dispatchEvent(a(b.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};h.prototype.handleMutations=function(a){var b=this;l(a,function(a){return l(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(k(a)?b.loadImport(a):b.loadImports(a))})})};if(m){var z=document.querySelectorAll("link[rel=import]");l(z,function(a){a.import&&
"loading"===a.import.readyState||(a.__loaded=!0)});z=function(a){a=a.target;k(a)&&(a.__loaded=!0)};document.addEventListener("load",z,!0);document.addEventListener("error",z,!0)}else{var y=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!y||y.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=k(this)?this:d(this);return a?a.href:y&&y.get?y.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});f(function(){return new h})}e(function(){return document.dispatchEvent(a("HTMLImportsLoaded",
{cancelable:!0,bubbles:!0,detail:void 0}))});b.useNative=m;b.whenReady=e;b.importForElement=d})(window.HTMLImports=window.HTMLImports||{});var pa=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));n.prototype.setDefinition=function(b,a){this._localNameToDefinition.set(b,a);this._constructorToDefinition.set(a.constructor,a)};n.prototype.localNameToDefinition=function(b){return this._localNameToDefinition.get(b)};n.prototype.constructorToDefinition=
function(b){return this._constructorToDefinition.get(b)};n.prototype.addPatch=function(b){this._hasPatches=!0;this._patches.push(b)};n.prototype.patchTree=function(b){var a=this;this._hasPatches&&q(b,function(b){return a.patch(b)})};n.prototype.patch=function(b){if(this._hasPatches&&!b.__CE_patched){b.__CE_patched=!0;for(var a=0;a<this._patches.length;a++)this._patches[a](b)}};n.prototype.connectTree=function(b){var a=[];q(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var d=a[b];1===d.__CE_state?
this.connectedCallback(d):this.upgradeElement(d)}};n.prototype.disconnectTree=function(b){var a=[];q(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var d=a[b];1===d.__CE_state&&this.disconnectedCallback(d)}};n.prototype.patchAndUpgradeTree=function(b,a){var d=this;a=void 0===a?new Set:a;var c=[];q(b,function(b){if("link"===b.localName&&"import"===b.getAttribute("rel")){var e=b.import;e instanceof Node&&"complete"===e.readyState?(e.__CE_isImportDocument=!0,e.__CE_hasRegistry=!0):b.addEventListener("load",
function(){var c=b.import;c.__CE_documentLoadHandled||(c.__CE_documentLoadHandled=!0,c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0,new Set(a),a.delete(c),d.patchAndUpgradeTree(c,a))})}else c.push(b)},a);if(this._hasPatches)for(b=0;b<c.length;b++)this.patch(c[b]);for(b=0;b<c.length;b++)this.upgradeElement(c[b])};n.prototype.upgradeElement=function(b){if(void 0===b.__CE_state){var a=this.localNameToDefinition(b.localName);if(a){a.constructionStack.push(b);var d=a.constructor;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");
}finally{a.constructionStack.pop()}}catch(e){throw b.__CE_state=2,e;}b.__CE_state=1;b.__CE_definition=a;if(a.attributeChangedCallback)for(a=a.observedAttributes,d=0;d<a.length;d++){var c=a[d],f=b.getAttribute(c);null!==f&&this.attributeChangedCallback(b,c,null,f,null)}k(b)&&this.connectedCallback(b)}}};n.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};n.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&
a.disconnectedCallback.call(b)};n.prototype.attributeChangedCallback=function(b,a,d,c,f){var e=b.__CE_definition;e.attributeChangedCallback&&-1<e.observedAttributes.indexOf(a)&&e.attributeChangedCallback.call(b,a,d,c,f)};F.prototype.disconnect=function(){this._observer&&this._observer.disconnect()};F.prototype._handleMutations=function(b){var a=this._document.readyState;"interactive"!==a&&"complete"!==a||this.disconnect();for(a=0;a<b.length;a++)for(var d=b[a].addedNodes,c=0;c<d.length;c++)this._internals.patchAndUpgradeTree(d[c])};
G.prototype.resolve=function(b){if(this._value)throw Error("Already resolved.");this._value=b;this._resolve&&this._resolve(b)};G.prototype.toPromise=function(){return this._promise};l.prototype.define=function(b,a){var d=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!U(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this._internals.localNameToDefinition(b))throw Error("A custom element with name '"+b+"' has already been defined.");
if(this._elementDefinitionIsRunning)throw Error("A custom element is already being defined.");this._elementDefinitionIsRunning=!0;try{var c=function(a){var b=f[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");return b},f=a.prototype;if(!(f instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var e=c("connectedCallback");var g=c("disconnectedCallback");var h=c("adoptedCallback");var k=c("attributeChangedCallback");
var l=a.observedAttributes||[]}catch(ra){return}finally{this._elementDefinitionIsRunning=!1}this._internals.setDefinition(b,{localName:b,constructor:a,connectedCallback:e,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]});this._unflushedLocalNames.push(b);this._flushPending||(this._flushPending=!0,this._flushCallback(function(){return d._flush()}))};l.prototype._flush=function(){if(!1!==this._flushPending)for(this._flushPending=!1,this._internals.patchAndUpgradeTree(document);0<
this._unflushedLocalNames.length;){var b=this._unflushedLocalNames.shift();(b=this._whenDefinedDeferred.get(b))&&b.resolve(void 0)}};l.prototype.get=function(b){if(b=this._internals.localNameToDefinition(b))return b.constructor};l.prototype.whenDefined=function(b){if(!U(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this._whenDefinedDeferred.get(b);if(a)return a.toPromise();a=new G;this._whenDefinedDeferred.set(b,a);this._internals.localNameToDefinition(b)&&
-1===this._unflushedLocalNames.indexOf(b)&&a.resolve(void 0);return a.toPromise()};l.prototype.polyfillWrapFlushCallback=function(b){this._documentConstructionObserver.disconnect();var a=this._flushCallback;this._flushCallback=function(d){return b(function(){return a(d)})}};window.CustomElementRegistry=l;l.prototype.define=l.prototype.define;l.prototype.get=l.prototype.get;l.prototype.whenDefined=l.prototype.whenDefined;l.prototype.polyfillWrapFlushCallback=l.prototype.polyfillWrapFlushCallback;var B=
window.Document.prototype.createElement,ka=window.Document.prototype.createElementNS,ja=window.Document.prototype.importNode,la=window.Document.prototype.prepend,ma=window.Document.prototype.append,J=window.Node.prototype.cloneNode,v=window.Node.prototype.appendChild,R=window.Node.prototype.insertBefore,C=window.Node.prototype.removeChild,S=window.Node.prototype.replaceChild,E=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),I=window.Element.prototype.attachShadow,t=Object.getOwnPropertyDescriptor(window.Element.prototype,
"innerHTML"),D=window.Element.prototype.getAttribute,K=window.Element.prototype.setAttribute,M=window.Element.prototype.removeAttribute,w=window.Element.prototype.getAttributeNS,L=window.Element.prototype.setAttributeNS,N=window.Element.prototype.removeAttributeNS,P=window.Element.prototype.insertAdjacentElement,Z=window.Element.prototype.prepend,aa=window.Element.prototype.append,ca=window.Element.prototype.before,da=window.Element.prototype.after,ea=window.Element.prototype.replaceWith,fa=window.Element.prototype.remove,
oa=window.HTMLElement,A=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),O=window.HTMLElement.prototype.insertAdjacentElement,T=new function(){},h=window.customElements;if(!h||h.forcePolyfill||"function"!=typeof h.define||"function"!=typeof h.get)h=new n,na(h),ia(h),ha(h),Y(h),document.__CE_hasRegistry=!0,h=new l(h),Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:h});h=window.customElements;var x=window.HTMLImports;window.WebComponents=window.WebComponents||
{};if(h&&h.polyfillWrapFlushCallback){var u,V=function(){if(u){var b=u;u=null;b();return!0}},W=x.whenReady;h.polyfillWrapFlushCallback(function(b){u=b;W(V)});x.whenReady=function(b){W(function(){V()?x.whenReady(b):b()})}}x.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});h=document.createElement("style");h.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";
var X=document.querySelector("head");X.insertBefore(h,X.firstChild)})();}).call(this);

//# sourceMappingURL=webcomponents-hi-ce.js.map
