(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var O=O||{};O.scope={};O.getGlobal=function(k){return"undefined"!=typeof window&&window===k?k:"undefined"!=typeof global&&null!=global?global:k};O.global=O.getGlobal(this);
(function(){function k(){var a=this;this._scopeCounter={};this._documentOwner=document.documentElement;var b=new Ka;b.rules=[];this._documentOwnerStyleInfo=t.set(this._documentOwner,new t(b));this._elementsHaveApplied=!1;this._customStyleInterface=this._applyShim=null;Kb(function(){a._ensure()})}function F(){this.customStyles=[];this.enqueued=!1}function Lb(){}function oa(a){this.cache={};this.typeMax=void 0===a?100:a}function p(){}function t(a,b,c,d,e,f){this.styleRules=a||null;this.placeholder=
b||null;this.ownStylePropertyNames=c||[];this.overrideStyleProperties=null;this.elementName=d||"";this.cssBuild=f||"";this.typeExtension=e||"";this.customStyle=this.scopeSelector=this.styleProperties=null}function r(){}function Ka(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}function Hd(a){function b(b,c){Object.defineProperty(b,"innerHTML",{enumerable:c.enumerable,
configurable:!0,get:c.get,set:function(b){var d=this,e=void 0;n(this)&&(e=[],P(this,function(a){a!==d&&e.push(a)}));c.set.call(this,b);if(e)for(var f=0;f<e.length;f++){var g=e[f];1===g.__CE_state&&a.disconnectedCallback(g)}this.ownerDocument.__CE_hasRegistry?a.patchAndUpgradeTree(this):a.patchTree(this);return b}})}function c(b,c){w(b,"insertAdjacentElement",function(b,d){var e=n(d);b=c.call(this,b,d);e&&a.disconnectTree(d);n(b)&&a.connectTree(d);return b})}Mb?w(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=
a=Mb.call(this,a)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(Ma&&Ma.get)b(Element.prototype,Ma);else if(Na&&Na.get)b(HTMLElement.prototype,Na);else{var d=Oa.call(document,"div");a.addPatch(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){return Nb.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName?this.content:this;for(d.innerHTML=a;0<b.childNodes.length;)Pa.call(b,b.childNodes[0]);for(;0<d.childNodes.length;)qa.call(b,d.childNodes[0])}})})}w(Element.prototype,
"setAttribute",function(b,c){if(1!==this.__CE_state)return Ob.call(this,b,c);var d=Qa.call(this,b);Ob.call(this,b,c);c=Qa.call(this,b);a.attributeChangedCallback(this,b,d,c,null)});w(Element.prototype,"setAttributeNS",function(b,c,d){if(1!==this.__CE_state)return Pb.call(this,b,c,d);var e=ra.call(this,b,c);Pb.call(this,b,c,d);d=ra.call(this,b,c);a.attributeChangedCallback(this,c,e,d,b)});w(Element.prototype,"removeAttribute",function(b){if(1!==this.__CE_state)return Qb.call(this,b);var c=Qa.call(this,
b);Qb.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)});w(Element.prototype,"removeAttributeNS",function(b,c){if(1!==this.__CE_state)return Rb.call(this,b,c);var d=ra.call(this,b,c);Rb.call(this,b,c);var e=ra.call(this,b,c);d!==e&&a.attributeChangedCallback(this,c,d,e,b)});Sb?c(HTMLElement.prototype,Sb):Tb?c(Element.prototype,Tb):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");Ub(a,Element.prototype,{prepend:Id,append:Jd});Kd(a,Element.prototype,
{before:Ld,after:Md,replaceWith:Nd,remove:Od})}function Kd(a,b,c){b.before=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&n(a)});c.before.apply(this,d);for(var g=0;g<f.length;g++)a.disconnectTree(f[g]);if(n(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.connectTree(g)};b.after=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&n(a)});c.after.apply(this,
d);for(var g=0;g<f.length;g++)a.disconnectTree(f[g]);if(n(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.connectTree(g)};b.replaceWith=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&n(a)});var g=n(this);c.replaceWith.apply(this,d);for(var h=0;h<f.length;h++)a.disconnectTree(f[h]);if(g)for(a.disconnectTree(this),f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.connectTree(g)};b.remove=function(){var b=n(this);c.remove.call(this);
b&&a.disconnectTree(this)}}function Pd(a){function b(b,d){Object.defineProperty(b,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,b);else{var c=void 0;if(this.firstChild){var e=this.childNodes,h=e.length;if(0<h&&n(this)){c=Array(h);for(var m=0;m<h;m++)c[m]=e[m]}}d.set.call(this,b);if(c)for(b=0;b<c.length;b++)a.disconnectTree(c[b])}}})}w(Node.prototype,"insertBefore",function(b,d){if(b instanceof DocumentFragment){var c=
Array.prototype.slice.apply(b.childNodes);b=Vb.call(this,b,d);if(n(this))for(d=0;d<c.length;d++)a.connectTree(c[d]);return b}c=n(b);d=Vb.call(this,b,d);c&&a.disconnectTree(b);n(this)&&a.connectTree(b);return d});w(Node.prototype,"appendChild",function(b){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=qa.call(this,b);if(n(this))for(var e=0;e<c.length;e++)a.connectTree(c[e]);return b}c=n(b);e=qa.call(this,b);c&&a.disconnectTree(b);n(this)&&a.connectTree(b);return e});
w(Node.prototype,"cloneNode",function(b){b=Nb.call(this,b);this.ownerDocument.__CE_hasRegistry?a.patchAndUpgradeTree(b):a.patchTree(b);return b});w(Node.prototype,"removeChild",function(b){var c=n(b),e=Pa.call(this,b);c&&a.disconnectTree(b);return e});w(Node.prototype,"replaceChild",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=Wb.call(this,b,d);if(n(this))for(a.disconnectTree(d),d=0;d<c.length;d++)a.connectTree(c[d]);return b}c=n(b);var f=Wb.call(this,
b,d),g=n(this);g&&a.disconnectTree(d);c&&a.disconnectTree(b);g&&a.connectTree(b);return f});Ra&&Ra.get?b(Node.prototype,Ra):a.addPatch(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)Pa.call(this,this.firstChild);qa.call(this,document.createTextNode(a))}})})}function Qd(a){w(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=
a.localNameToDefinition(b);if(c)return new c.constructor}b=Oa.call(this,b);a.patch(b);return b});w(Document.prototype,"importNode",function(b,c){b=Rd.call(this,b,c);this.__CE_hasRegistry?a.patchAndUpgradeTree(b):a.patchTree(b);return b});w(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.localNameToDefinition(c);if(d)return new d.constructor}b=Sd.call(this,b,c);a.patch(b);return b});Ub(a,Document.prototype,{prepend:Td,
append:Ud})}function Ub(a,b,c){b.prepend=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&n(a)});c.prepend.apply(this,d);for(var g=0;g<f.length;g++)a.disconnectTree(f[g]);if(n(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.connectTree(g)};b.append=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&n(a)});c.append.apply(this,d);for(var g=0;g<f.length;g++)a.disconnectTree(f[g]);
if(n(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.connectTree(g)}}function Vd(a){window.HTMLElement=function(){function b(){var b=this.constructor,d=a.constructorToDefinition(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=Oa.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.patch(e),e;d=e.length-1;var f=e[d];if(f===Xb)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[d]=Xb;Object.setPrototypeOf(f,b.prototype);a.patch(f);return f}b.prototype=Wd.prototype;return b}()}function z(a){this._elementDefinitionIsRunning=!1;this._internals=a;this._whenDefinedDeferred=new Map;this._flushCallback=function(a){return a()};this._flushPending=!1;this._unflushedLocalNames=[];this._documentConstructionObserver=new Sa(a,document)}function Ta(){var a=this;this._resolve=this._value=void 0;this._promise=new Promise(function(b){a._resolve=b;a._value&&b(a._value)})}function Sa(a,b){this._internals=
a;this._document=b;this._observer=void 0;this._internals.patchAndUpgradeTree(this._document);"loading"===this._document.readyState&&(this._observer=new MutationObserver(this._handleMutations.bind(this)),this._observer.observe(this._document,{childList:!0,subtree:!0}))}function u(){this._localNameToDefinition=new Map;this._constructorToDefinition=new Map;this._patches=[];this._hasPatches=!1}function l(a,b,c){if(a!==Yb)throw new TypeError("Illegal constructor");a=document.createDocumentFragment();a.__proto__=
l.prototype;a._init(b,c);return a}function sa(a){if(!a.__shady||void 0===a.__shady.firstChild){a.__shady=a.__shady||{};a.__shady.firstChild=Ua(a);a.__shady.lastChild=Va(a);Zb(a);for(var b=a.__shady.childNodes=U(a),c=0,d;c<b.length&&(d=b[c]);c++)d.__shady=d.__shady||{},d.__shady.parentNode=a,d.__shady.nextSibling=b[c+1]||null,d.__shady.previousSibling=b[c-1]||null,$b(d)}}function Xd(a){var b=a&&a._observer;b&&(b.callbacks.delete(a._callback),b.callbacks.size||(a._node.__shady.observer=null))}function Yd(a,
b){a.__shady=a.__shady||{};a.__shady.observer||(a.__shady.observer=new ta);a.__shady.observer.callbacks.add(b);var c=a.__shady.observer;return{_callback:b,_observer:c,_node:a,takeRecords:function(){return c.takeRecords()}}}function ta(){this._scheduled=!1;this.addedNodes=[];this.removedNodes=[];this.callbacks=new Set}function Q(a,b){V[W]=a;V[W+1]=b;W+=2;2===W&&(Wa?Wa(X):Zd())}function $d(){return function(){return process.nextTick(X)}}function ae(){return"undefined"!==typeof Xa?function(){Xa(X)}:
Ya()}function be(){var a=0,b=new ac(X),c=document.createTextNode("");b.observe(c,{characterData:!0});return function(){c.data=a=++a%2}}function ce(){var a=new MessageChannel;a.port1.onmessage=X;return function(){return a.port2.postMessage(0)}}function Ya(){var a=setTimeout;return function(){return a(X,1)}}function X(){for(var a=0;a<W;a+=2)(0,V[a])(V[a+1]),V[a]=void 0,V[a+1]=void 0;W=0}function de(){try{var a=require("vertx");Xa=a.runOnLoop||a.runOnContext;return ae()}catch(b){return Ya()}}function Za(a,
b){var c=this,d=new this.constructor(Y);void 0===d[ua]&&bc(d);var e=c._state;if(e){var f=arguments[e-1];Q(function(){return cc(e,d,f,c._result)})}else $a(c,d,a,b);return d}function ab(a){if(a&&"object"===typeof a&&a.constructor===this)return a;var b=new this(Y);ea(b,a);return b}function Y(){}function dc(a){try{return a.then}catch(b){return fa.error=b,fa}}function ee(a,b,c,d){try{a.call(b,c,d)}catch(e){return e}}function fe(a,b,c){Q(function(a){var d=!1,f=ee(c,b,function(c){d||(d=!0,b!==c?ea(a,c):
J(a,c))},function(b){d||(d=!0,A(a,b))},"Settle: "+(a._label||" unknown promise"));!d&&f&&(d=!0,A(a,f))},a)}function ge(a,b){1===b._state?J(a,b._result):2===b._state?A(a,b._result):$a(b,void 0,function(b){return ea(a,b)},function(b){return A(a,b)})}function ec(a,b,c){b.constructor===a.constructor&&c===Za&&b.constructor.resolve===ab?ge(a,b):c===fa?(A(a,fa.error),fa.error=null):void 0===c?J(a,b):"function"===typeof c?fe(a,b,c):J(a,b)}function ea(a,b){if(a===b)A(a,new TypeError("You cannot resolve a promise with itself"));
else{var c=typeof b;null===b||"object"!==c&&"function"!==c?J(a,b):ec(a,b,dc(b))}}function he(a){a._onerror&&a._onerror(a._result);bb(a)}function J(a,b){void 0===a._state&&(a._result=b,a._state=1,0!==a._subscribers.length&&Q(bb,a))}function A(a,b){void 0===a._state&&(a._state=2,a._result=b,Q(he,a))}function $a(a,b,c,d){var e=a._subscribers,f=e.length;a._onerror=null;e[f]=b;e[f+1]=c;e[f+2]=d;0===f&&a._state&&Q(bb,a)}function bb(a){var b=a._subscribers,c=a._state;if(0!==b.length){for(var d,e,f=a._result,
g=0;g<b.length;g+=3)d=b[g],e=b[g+c],d?cc(c,d,e,f):e(f);a._subscribers.length=0}}function fc(){this.error=null}function cc(a,b,c,d){var e="function"===typeof c;if(e){try{var f=c(d)}catch(pa){cb.error=pa,f=cb}if(f===cb){var g=!0;var h=f.error;f.error=null}else var m=!0;if(b===f){A(b,new TypeError("A promises callback cannot return that same promise."));return}}else f=d,m=!0;void 0===b._state&&(e&&m?ea(b,f):g?A(b,h):1===a?J(b,f):2===a&&A(b,f))}function ie(a,b){try{b(function(b){ea(a,b)},function(b){A(a,
b)})}catch(c){A(a,c)}}function bc(a){a[ua]=gc++;a._state=void 0;a._result=void 0;a._subscribers=[]}function ha(a,b){this._instanceConstructor=a;this.promise=new a(Y);this.promise[ua]||bc(this.promise);hc(b)?(this._remaining=this.length=b.length,this._result=Array(this.length),0===this.length?J(this.promise,this._result):(this.length=this.length||0,this._enumerate(b),0===this._remaining&&J(this.promise,this._result))):A(this.promise,Error("Array Methods must be provided an Array"))}function q(a){this[ua]=
gc++;this._result=this._state=void 0;this._subscribers=[];if(Y!==a){if("function"!==typeof a)throw new TypeError("You must pass a resolver function as the first argument to the promise constructor");if(this instanceof q)ie(this,a);else throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");}}function Z(a){return a.__shady&&void 0!==a.__shady.firstChild}function H(a){return"ShadyRoot"===a.__localName}function ia(a){a=
a.getRootNode();if(H(a))return a}function db(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=e,g=a,h=Object.getOwnPropertyDescriptor(b,f);h&&Object.defineProperty(g,f,h)}return a||b}function eb(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)db(a,c[d]);return a}function je(a,b){for(var c in b)a[c]=b[c];return a}function ic(a){fb.push(a);gb.textContent=jc++}function kc(a){hb||(hb=!0,ic(va));ja.push(a)}function va(){hb=
!1;for(var a=!!ja.length;ja.length;)ja.shift()();return a}function ke(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})}function lc(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";
case "\u00a0":return"&nbsp;"}}function mc(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}function ib(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g;e<f&&(g=d[e]);e++){a:{var h=g;var m=a;var pa=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var k=h.localName,l="<"+k,n=h.attributes,p=0;m=n[p];p++)l+=" "+m.name+'="'+m.value.replace(le,lc)+'"';l+=">";h=me[k]?l:l+ib(h,pa)+"</"+k+">";break a;case Node.TEXT_NODE:h=h.data;h=m&&ne[m.localName]?h:h.replace(oe,
lc);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),Error("not implemented");}}c+=h}return c}function aa(a){B.currentNode=a;return B.parentNode()}function Ua(a){B.currentNode=a;return B.firstChild()}function Va(a){B.currentNode=a;return B.lastChild()}function nc(a){B.currentNode=a;return B.previousSibling()}function oc(a){B.currentNode=a;return B.nextSibling()}function U(a){var b=[];B.currentNode=a;for(a=B.firstChild();a;)b.push(a),a=B.nextSibling();
return b}function pc(a){C.currentNode=a;return C.parentNode()}function qc(a){C.currentNode=a;return C.firstChild()}function rc(a){C.currentNode=a;return C.lastChild()}function sc(a){C.currentNode=a;return C.previousSibling()}function tc(a){C.currentNode=a;return C.nextSibling()}function uc(a){var b=[];C.currentNode=a;for(a=C.firstChild();a;)b.push(a),a=C.nextSibling();return b}function vc(a){return ib(a,function(a){return U(a)})}function wc(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=
document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}}function L(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function R(a){L(a,xc);L(a,jb);L(a,kb)}function yc(a,b,c){$b(a);c=c||null;a.__shady=a.__shady||{};b.__shady=b.__shady||{};c&&(c.__shady=c.__shady||{});a.__shady.previousSibling=c?c.__shady.previousSibling:
b.lastChild;var d=a.__shady.previousSibling;d&&d.__shady&&(d.__shady.nextSibling=a);(d=a.__shady.nextSibling=c)&&d.__shady&&(d.__shady.previousSibling=a);a.__shady.parentNode=b;c?c===b.__shady.firstChild&&(b.__shady.firstChild=a):(b.__shady.lastChild=a,b.__shady.firstChild||(b.__shady.firstChild=a));b.__shady.childNodes=null}function lb(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=c.__shady&&c.__shady.parentNode;if(void 0!==
d&&d!==a||void 0===d&&aa(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&mb(b.parentNode,b);d=ia(a);var e;if(e=d)a:{if(!b.__noInsertionPoint){var f;"slot"===b.localName?f=[b]:b.querySelectorAll&&(f=b.querySelectorAll("slot"));if(f&&f.length){e=f;break a}}e=void 0}f=e;d&&("slot"===a.localName||f)&&d._asyncRender();if(Z(a)){e=c;Zb(a);a.__shady=a.__shady||{};void 0!==a.__shady.firstChild&&
(a.__shady.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){for(var g=b.childNodes,h=0;h<g.length;h++)yc(g[h],a,e);b.__shady=b.__shady||{};e=void 0!==b.__shady.firstChild?null:void 0;b.__shady.firstChild=b.__shady.lastChild=e;b.__shady.childNodes=e}else yc(b,a,e);if(nb(a)){a.__shady.root._asyncRender();var m=!0}else a.__shady.root&&(m=!0)}m||(m=H(a)?a.host:a,c?(c=zc(c),ob.call(m,b,c)):Ac.call(m,b));Bc(a,b);f&&d._addSlots(f);return b}function mb(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+
b);var c=ia(b);if(Z(a)){b.__shady=b.__shady||{};a.__shady=a.__shady||{};b===a.__shady.firstChild&&(a.__shady.firstChild=b.__shady.nextSibling);b===a.__shady.lastChild&&(a.__shady.lastChild=b.__shady.previousSibling);var d=b.__shady.previousSibling;var e=b.__shady.nextSibling;d&&(d.__shady=d.__shady||{},d.__shady.nextSibling=e);e&&(e.__shady=e.__shady||{},e.__shady.previousSibling=d);b.__shady.parentNode=b.__shady.previousSibling=b.__shady.nextSibling=void 0;void 0!==a.__shady.childNodes&&(a.__shady.childNodes=
null);if(nb(a)){a.__shady.root._asyncRender();var f=!0}}Cc(b);c&&((e=a&&"slot"===a.localName)&&(f=!0),((d=c._removeContainedSlots(b))||e)&&c._asyncRender());f||(f=H(a)?a.host:a,(!a.__shady.root&&"slot"!==b.localName||f===aa(b))&&ka.call(f,b));Bc(a,null,b);return b}function Cc(a){if(a.__shady&&void 0!==a.__shady.ownerShadyRoot)for(var b=a.childNodes,c=0,d=b.length,e;c<d&&(e=b[c]);c++)Cc(e);a.__shady&&(a.__shady.ownerShadyRoot=void 0)}function zc(a){var b=a;a&&"slot"===a.localName&&(b=(b=a.__shady&&
a.__shady.flattenedNodes)&&b.length?b[0]:zc(a.nextSibling));return b}function nb(a){return(a=a&&a.__shady&&a.__shady.root)&&a._hasInsertionPoint()}function Dc(a,b){"slot"===b?(a=a.parentNode,nb(a)&&a.__shady.root._asyncRender()):"slot"===a.localName&&"name"===b&&(b=ia(a))&&(b._updateSlotName(a),b._asyncRender())}function Bc(a,b,c){if(a=a.__shady&&a.__shady.observer)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),a.schedule()}function Ec(a){if(a&&a.nodeType){a.__shady=a.__shady||{};var b=a.__shady.ownerShadyRoot;
void 0===b&&(b=H(a)?a:(b=a.parentNode)?Ec(b):a,document.documentElement.contains(a)&&(a.__shady.ownerShadyRoot=b));return b}}function wa(a,b,c){var d=[];Fc(a.childNodes,b,c,d);return d}function Fc(a,b,c,d){for(var e=0,f=a.length,g;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var m=b,k=c,La=d,l=m(h);l&&La.push(h);k&&k(l)?h=l:(Fc(h.childNodes,m,k,La),h=void 0)}if(h)return!0}}function Gc(a){a=a.getRootNode();H(a)&&a._render()}function Hc(a,b,c){xa||(xa=window.ShadyCSS&&window.ShadyCSS.ScopingShim);
xa&&"class"===b?xa.setElementClass(a,c):(Ic.call(a,b,c),Dc(a,b))}function Jc(a,b){if(a.ownerDocument!==document)return pb.call(document,a,b);var c=pb.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=Jc(a[b],!0),c.appendChild(d)}return c}function qb(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}
function Kc(a,b){if(!H)return a;a=qb(a,!0);for(var c=0,d,e,f,g;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!H(f)||-1<g)return d}function rb(a){function b(b,d){b=new a(b,d);b.__composed=d&&!!d.composed;return b}je(b,a);b.prototype=a.prototype;return b}function Lc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&a.target!==a.relatedTarget&&(e.call(b,a),!a.__immediatePropagationStopped);d++);}function pe(a){var b=
a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];Lc(a,d,"capture");if(a.__propagationStopped)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=d.__shady&&d.__shady.root;if(0===c||f&&f===e)if(Lc(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.__propagationStopped)break}}function Mc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=
a[g],m=h.type,k=h.capture,l=h.once,n=h.passive;if(b===h.node&&c===m&&d===k&&e===l&&f===n)return g}return-1}function Nc(a,b,c){if(b){if("object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var g=c&&c.__shadyTarget||this,h=b.__eventWrappers;if(h){if(-1<Mc(h,g,a,d,e,f))return}else b.__eventWrappers=[];h=function(d){e&&this.removeEventListener(a,b,c);d.__target||Oc(d);if(g!==this){var f=Object.getOwnPropertyDescriptor(d,"currentTarget");Object.defineProperty(d,"currentTarget",
{get:function(){return g},configurable:!0})}if(d.composed||-1<d.composedPath().indexOf(g))if(d.target===d.relatedTarget)d.eventPhase===Event.BUBBLING_PHASE&&d.stopImmediatePropagation();else if(d.eventPhase===Event.CAPTURING_PHASE||d.bubbles||d.target===g){var h="object"===typeof b&&b.handleEvent?b.handleEvent(d):b.call(g,d);g!==this&&(f?(Object.defineProperty(d,"currentTarget",f),f=null):delete d.currentTarget);return h}};b.__eventWrappers.push({node:this,type:a,capture:d,once:e,passive:f,wrapperFn:h});
sb[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][d?"capture":"bubble"].push(h)):(this instanceof Window?Pc:Qc).call(this,a,h,c)}}function Rc(a,b,c){if(b){if("object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var g=c&&c.__shadyTarget||this,h=void 0;var m=null;try{m=b.__eventWrappers}catch(pa){}m&&(e=Mc(m,g,a,d,e,f),-1<e&&(h=m.splice(e,1)[0].wrapperFn,m.length||(b.__eventWrappers=void 0)));
(this instanceof Window?Sc:Tc).call(this,a,h||b,c);h&&sb[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],h=a.indexOf(h),-1<h&&a.splice(h,1))}}function qe(){for(var a in sb)window.addEventListener(a,function(a){a.__target||(Oc(a),pe(a))},!0)}function Oc(a){a.__target=a.target;a.__relatedTarget=a.relatedTarget;if(D.hasDescriptors){var b=Uc,c=Object.getPrototypeOf(a);if(!c.hasOwnProperty("__patchProto")){var d=Object.create(c);d.__sourceProto=c;db(d,b);c.__patchProto=
d}a.__proto__=c.__patchProto}else db(a,Uc)}function la(a,b,c){return{index:a,removed:b,addedCount:c}}function re(a,b,c,d,e,f){var g=0,h=0,m=Math.min(c-b,f-e);if(0==b&&0==e)a:{for(g=0;g<m;g++)if(a[g]!==d[g])break a;g=m}if(c==a.length&&f==d.length){h=m-g;m=a.length;for(var k=d.length,l=0;l<h&&se(a[--m],d[--k]);)l++;h=l}b+=g;e+=g;c-=h;f-=h;if(0==c-b&&0==f-e)return[];if(b==c){for(c=la(b,[],0);e<f;)c.removed.push(d[e++]);return[c]}if(e==f)return[la(b,[],c-b)];g=b;h=e;f=f-h+1;m=c-g+1;c=Array(f);for(k=0;k<
f;k++)c[k]=Array(m),c[k][0]=k;for(k=0;k<m;k++)c[0][k]=k;for(k=1;k<f;k++)for(l=1;l<m;l++)if(a[g+l-1]===d[h+k-1])c[k][l]=c[k-1][l-1];else{var n=c[k-1][l]+1,p=c[k][l-1]+1;c[k][l]=n<p?n:p}f=c.length-1;g=c[0].length-1;h=c[f][g];for(a=[];0<f||0<g;)0==f?(a.push(2),g--):0==g?(a.push(3),f--):(m=c[f-1][g-1],k=c[f-1][g],l=c[f][g-1],n=k<l?k<m?k:m:l<m?l:m,n==m?(m==h?a.push(0):(a.push(1),h=m),f--,g--):n==k?(a.push(3),f--,h=k):(a.push(2),g--,h=l));a.reverse();c=void 0;f=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:c&&
(f.push(c),c=void 0);b++;e++;break;case 1:c||(c=la(b,[],0));c.addedCount++;b++;c.removed.push(d[e]);e++;break;case 2:c||(c=la(b,[],0));c.addedCount++;b++;break;case 3:c||(c=la(b,[],0)),c.removed.push(d[e]),e++}c&&f.push(c);return f}function se(a,b){return a===b}function Vc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}function Wc(a){Gc(a);return a.__shady&&a.__shady.assignedSlot||null}function M(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,
e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}}function te(){var a=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;M(window.Node.prototype,ue);M(window.Window.prototype,ve);M(window.Text.prototype,we);M(window.DocumentFragment.prototype,tb);M(window.Element.prototype,Xc);M(window.Document.prototype,Yc);window.HTMLSlotElement&&M(window.HTMLSlotElement.prototype,Zc);M(a.prototype,xe);D.hasDescriptors&&(R(window.Node.prototype),R(window.Text.prototype),R(window.DocumentFragment.prototype),
R(window.Element.prototype),R(a.prototype),R(window.Document.prototype),window.HTMLSlotElement&&R(window.HTMLSlotElement.prototype))}function $c(a){var b=ye.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function n(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}function ub(a,b){for(;b&&b!==
a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}function P(a,b,c){c=void 0===c?new Set:c;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)P(d,b,c);d=ub(a,e);continue}else if("template"===f){d=ub(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)P(e,b,c)}d=d.firstChild?d.firstChild:ub(a,
d)}}function w(a,b,c){a[b]=c}function vb(a){a=a.replace(G.comments,"").replace(G.port,"");var b=ad,c=a,d=new Ka;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,m=h.rules[h.rules.length-1]||null;e=new Ka;e.start=f+1;e.parent=h;e.previous=m;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}function ad(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:
a.parent.start,a.start-1),c=ze(c),c=c.replace(G.multipleSpaces," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=K.MEDIA_RULE:c.match(G.keyframesRule)&&(a.type=K.KEYFRAMES_RULE,a.keyframesName=a.selector.split(G.multipleSpaces).pop()):0===c.indexOf("--")?a.type=K.MIXIN_RULE:a.type=K.STYLE_RULE);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)ad(f,b);return a}function ze(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,
function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}function bd(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h;f<g&&(h=e[f]);f++)d=bd(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(G.customProp,"").replace(G.mixinProp,""),b=b.replace(G.mixinApply,"").replace(G.varApply,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));
return c}function cd(a){x=a&&a.shimcssproperties?!1:y||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}function ba(a,b){if(!a)return"";"string"===typeof a&&(a=vb(a));b&&ca(a,b);return bd(a,x)}function ya(a){!a.__cssRules&&a.textContent&&(a.__cssRules=vb(a.textContent));return a.__cssRules||null}function dd(a){return!!a.parent&&a.parent.type===K.KEYFRAMES_RULE}function ca(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===
K.MEDIA_RULE){var g=a.selector.match(Ae);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===K.STYLE_RULE?b(a):c&&f===K.KEYFRAMES_RULE?c(a):f===K.MIXIN_RULE&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var h;e<f&&(h=a[e]);e++)ca(h,b,c,d)}}}function wb(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;ed(e,c,d);return e}function ed(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);S?a.compareDocumentPosition(S)===Node.DOCUMENT_POSITION_PRECEDING&&
(S=a):S=a}function fd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var d=0;var e=c+3;for(var f=a.length;e<f;e++)if("("===a[e])d++;else if(")"===a[e]&&0===--d)break a;e=-1}d=a.substring(c+4,e);c=a.substring(0,c);a=fd(a.substring(e+1),b);f=d.indexOf(",");if(-1===f)return b(c,d.trim(),"",a);e=d.substring(0,f).trim();d=d.substring(f+1).trim();return b(c,e,d,a)}function za(a,b){y?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}function T(a){var b=
a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,typeExtension:c}}function gd(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var g=e;var h=[];g.classList?h=Array.from(g.classList):g instanceof window.SVGElement&&g.hasAttribute("class")&&(h=g.getAttribute("class").split(/\s+/));
g=h;h=g.indexOf(v.SCOPE_NAME);g=-1<h?g[h+1]:"";g&&f===e.ownerDocument?v.dom(e,g,!0):f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(f=f.host)&&(f=T(f).is,g!==f&&(g&&v.dom(e,g,!0),v.dom(e,f)))}}}}function Be(a){if(a=Aa[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function hd(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Ce(a){a._applyShimValidatingVersion=
a._applyShimNextVersion;a._validating||(a._validating=!0,De.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))}function Kb(a){requestAnimationFrame(function(){id?id(a):(xb||(xb=new Promise(function(a){yb=a}),"complete"===document.readyState?yb():document.addEventListener("readystatechange",function(){"complete"===document.readyState&&yb()})),xb.then(function(){a&&a()}))})}(function(){if(!function(){var a=document.createEvent("Event");a.initEvent("foo",!0,!0);a.preventDefault();
return a.defaultPrevented}()){var a=Event.prototype.preventDefault;Event.prototype.preventDefault=function(){this.cancelable&&(a.call(this),Object.defineProperty(this,"defaultPrevented",{get:function(){return!0},configurable:!0}))}}var b=/Trident/.test(navigator.userAgent);if(!window.CustomEvent||b&&"function"!==typeof window.CustomEvent)window.CustomEvent=function(a,b){b=b||{};var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c},window.CustomEvent.prototype=
window.Event.prototype;if(!window.Event||b&&"function"!==typeof window.Event){var c=window.Event;window.Event=function(a,b){b=b||{};var c=document.createEvent("Event");c.initEvent(a,!!b.bubbles,!!b.cancelable);return c};if(c)for(var d in c)window.Event[d]=c[d];window.Event.prototype=c.prototype}if(!window.MouseEvent||b&&"function"!==typeof window.MouseEvent){b=window.MouseEvent;window.MouseEvent=function(a,b){b=b||{};var c=document.createEvent("MouseEvent");c.initMouseEvent(a,!!b.bubbles,!!b.cancelable,
b.view||window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);return c};if(b)for(d in b)window.MouseEvent[d]=b[d];window.MouseEvent.prototype=b.prototype}Array.from||(Array.from=function(a){return[].slice.call(a)});Object.assign||(Object.assign=function(a,b){for(var c=[].slice.call(arguments,1),d=0,e;d<c.length;d++)if(e=c[d])for(var f=a,k=e,l=Object.getOwnPropertyNames(k),n=0;n<l.length;n++)e=l[n],f[e]=k[e];return a})})(window.WebComponents);
(function(){function a(){}var b="undefined"===typeof HTMLTemplateElement;/Trident/.test(navigator.userAgent)&&function(){var a=Document.prototype.importNode;Document.prototype.importNode=function(){var b=a.apply(this,arguments);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){var c=this.createDocumentFragment();c.appendChild(b);return c}return b}}();var c=Node.prototype.cloneNode,d=Document.prototype.createElement,e=Document.prototype.importNode,f=function(){if(!b){var a=document.createElement("template"),
c=document.createElement("template");c.content.appendChild(document.createElement("div"));a.content.appendChild(c);a=a.cloneNode(!0);return 0===a.content.childNodes.length||0===a.content.firstChild.content.childNodes.length||!(document.createDocumentFragment().cloneNode()instanceof DocumentFragment)}}();if(b){var g=function(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case "\u00a0":return"&nbsp;"}},h=function(b){Object.defineProperty(b,"innerHTML",{get:function(){for(var a=
"",b=this.content.firstChild;b;b=b.nextSibling)a+=b.outerHTML||b.data.replace(t,g);return a},set:function(b){k.body.innerHTML=b;for(a.bootstrap(k);this.content.firstChild;)this.content.removeChild(this.content.firstChild);for(;k.body.firstChild;)this.content.appendChild(k.body.firstChild)},configurable:!0})},k=document.implementation.createHTMLDocument("template"),l=!0,n=document.createElement("style");n.textContent="template{display:none;}";var p=document.head;p.insertBefore(n,p.firstElementChild);
a.prototype=Object.create(HTMLElement.prototype);var r=!document.createElement("div").hasOwnProperty("innerHTML");a.decorate=function(b){if(!b.content){b.content=k.createDocumentFragment();for(var c;c=b.firstChild;)b.content.appendChild(c);if(r)b.__proto__=a.prototype;else if(b.cloneNode=function(b){return a._cloneNode(this,b)},l)try{h(b)}catch(cf){l=!1}a.bootstrap(b.content)}};h(a.prototype);a.bootstrap=function(b){b=b.querySelectorAll("template");for(var c=0,d=b.length,e;c<d&&(e=b[c]);c++)a.decorate(e)};
document.addEventListener("DOMContentLoaded",function(){a.bootstrap(document)});Document.prototype.createElement=function(){var b=d.apply(this,arguments);"template"===b.localName&&a.decorate(b);return b};var t=/[&\u00A0<>]/g}if(b||f)a._cloneNode=function(a,b){var d=c.call(a,!1);this.decorate&&this.decorate(d);b&&(d.content.appendChild(c.call(a.content,!0)),this.fixClonedDom(d.content,a.content));return d},a.prototype.cloneNode=function(b){return a._cloneNode(this,b)},a.fixClonedDom=function(a,b){if(b.querySelectorAll){b=
b.querySelectorAll("template");a=a.querySelectorAll("template");for(var c=0,d=a.length,e,f;c<d;c++)f=b[c],e=a[c],this.decorate&&this.decorate(f),e.parentNode.replaceChild(f.cloneNode(!0),e)}},Node.prototype.cloneNode=function(b){if(this instanceof DocumentFragment)if(b)var d=this.ownerDocument.importNode(this,!0);else return this.ownerDocument.createDocumentFragment();else d=c.call(this,b);b&&a.fixClonedDom(d,this);return d},Document.prototype.importNode=function(b,c){if("template"===b.localName)return a._cloneNode(b,
c);var d=e.call(this,b,c);c&&a.fixClonedDom(d,b);return d},f&&(window.HTMLTemplateElement.prototype.cloneNode=function(b){return a._cloneNode(this,b)});b&&(window.HTMLTemplateElement=a)})();var hc=Array.isArray?Array.isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},W=0,Xa,Wa,jd="undefined"!==typeof window?window:void 0,kd=jd||{},ac=kd.MutationObserver||kd.WebKitMutationObserver,Ee="undefined"===typeof self&&"undefined"!==typeof process&&"[object process]"==={}.toString.call(process),
Fe="undefined"!==typeof Uint8ClampedArray&&"undefined"!==typeof importScripts&&"undefined"!==typeof MessageChannel,V=Array(1E3);var Zd=Ee?$d():ac?be():Fe?ce():void 0===jd&&"function"===typeof require?de():Ya();var ua=Math.random().toString(36).substring(16),fa=new fc,cb=new fc,gc=0;ha.prototype._enumerate=function(a){for(var b=0;void 0===this._state&&b<a.length;b++)this._eachEntry(a[b],b)};ha.prototype._eachEntry=function(a,b){var c=this._instanceConstructor,d=c.resolve;d===ab?(d=dc(a),d===Za&&void 0!==
a._state?this._settledAt(a._state,b,a._result):"function"!==typeof d?(this._remaining--,this._result[b]=a):c===q?(c=new c(Y),ec(c,a,d),this._willSettleAt(c,b)):this._willSettleAt(new c(function(b){return b(a)}),b)):this._willSettleAt(d(a),b)};ha.prototype._settledAt=function(a,b,c){var d=this.promise;void 0===d._state&&(this._remaining--,2===a?A(d,c):this._result[b]=c);0===this._remaining&&J(d,this._result)};ha.prototype._willSettleAt=function(a,b){var c=this;$a(a,void 0,function(a){return c._settledAt(1,
b,a)},function(a){return c._settledAt(2,b,a)})};q.all=function(a){return(new ha(this,a)).promise};q.race=function(a){var b=this;return hc(a)?new b(function(c,d){for(var e=a.length,f=0;f<e;f++)b.resolve(a[f]).then(c,d)}):new b(function(a,b){return b(new TypeError("You must pass an array to race."))})};q.resolve=ab;q.reject=function(a){var b=new this(Y);A(b,a);return b};q._setScheduler=function(a){Wa=a};q._setAsap=function(a){Q=a};q._asap=Q;q.prototype={constructor:q,then:Za,catch:function(a){return this.then(null,
a)}};q.polyfill=function(){if("undefined"!==typeof global)var a=global;else if("undefined"!==typeof self)a=self;else try{a=Function("return this")()}catch(d){throw Error("polyfill failed because global object is unavailable in this environment");}var b=a.Promise;if(b){var c=null;try{c=Object.prototype.toString.call(b.resolve())}catch(d){}if("[object Promise]"===c&&!b.cast)return}a.Promise=q};q.Promise=q;q.polyfill();(function(a){function b(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,
b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function c(a){if(n)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!h(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=document.querySelectorAll("link[rel=import]:not(import-dependency)"),c=b.length;c?l(b,function(b){return g(b,function(){0===
--c&&a()})}):a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function g(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,c);a.__loaded=!0;b&&b()};a.addEventListener("load",
c);x&&"style"===a.localName||a.addEventListener("error",c)}}function h(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function k(){var a=this;this.documents={};this.inflight=0;this.dynamicImportsMO=new MutationObserver(function(b){return a.handleMutations(b)});this.dynamicImportsMO.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function l(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var n="import"in document.createElement("link"),
p=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return p||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var r=/(^\/)|(^#)|(^[\w-\d]*:)/,t=/(url\()([^)]*)(\))/g,v=/(@import[\s]+(?!url\())([^;]*)(;)/g,y=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,q={fixUrls:function(a,b){a.href&&a.setAttribute("href",q.replaceAttrUrl(a.getAttribute("href"),b));a.src&&a.setAttribute("src",q.replaceAttrUrl(a.getAttribute("src"),
b));if("style"===a.localName){var c=q.replaceUrls(a.textContent,b,t);a.textContent=q.replaceUrls(c,b,v)}},replaceUrls:function(a,b,c){return a.replace(c,function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=q.resolveUrl(a,b));return c+"'"+a+"'"+e})},replaceAttrUrl:function(a,b){return a&&r.test(a)?a:q.resolveUrl(a,b)},resolveUrl:function(a,b){if(void 0===q.__workingURL){q.__workingURL=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";q.__workingURL="http://a/c%20d"===c.href}catch(df){}}if(q.__workingURL)return(new URL(a,
b)).href;c=q.__tempDoc;c||(c=document.implementation.createHTMLDocument("temp"),q.__tempDoc=c,c.__base=c.createElement("base"),c.head.appendChild(c.__base),c.__anchor=c.createElement("a"));c.__base.href=b;c.__anchor.href=a;return c.__anchor.href||a}},z={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,z.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");
a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},x=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);k.prototype.loadImports=function(a){var b=this;a=a.querySelectorAll("link[rel=import]");l(a,function(a){return b.loadImport(a)})};k.prototype.loadImport=function(a){var b=this,c=a.href;
if(void 0!==this.documents[c]){var d=this.documents[c];d&&d.__loaded&&(a.import=d,this.fireEventIfNeeded(a))}else this.inflight++,this.documents[c]="pending",z.load(c,function(a,d){a=b.makeDocument(a,d||c);b.documents[c]=a;b.inflight--;b.loadImports(a);b.processImportsIfLoadingDone()},function(){b.documents[c]=null;b.inflight--;b.processImportsIfLoadingDone()})};k.prototype.makeDocument=function(a,b){if(!a)return document.createDocumentFragment();x&&(a=a.replace(y,function(a,b,c){return-1===a.indexOf("type=")?
b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content;else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=q.replaceAttrUrl(c.getAttribute("href"),b),c.removeAttribute("href");c=a.querySelectorAll('link[rel=import], link[rel=stylesheet][href][type=import-disable],\n    style:not([type]), link[rel=stylesheet][href]:not([type]),\n    script:not([type]), script[type="application/javascript"],\n    script[type="text/javascript"]');
var d=0;l(c,function(a){g(a);q.fixUrls(a,b);a.setAttribute("import-dependency","");"script"===a.localName&&!a.src&&a.textContent&&(a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n"))),a.textContent="",d++)});return a};k.prototype.processImportsIfLoadingDone=function(){var a=this;if(!this.inflight){this.dynamicImportsMO.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.loadImports(document),a.inflight||
(a.dynamicImportsMO.observe(document.head,{childList:!0,subtree:!0}),a.fireEvents()))};this.waitForStyles(function(){c=!0;d()});this.runScripts(function(){b=!0;d()})}};k.prototype.flatten=function(a){var b=this;a=a.querySelectorAll("link[rel=import]");l(a,function(a){var c=b.documents[a.href];(a.import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.documents[a.href]=a,a.readyState="loading",a.import=a,b.flatten(c),a.appendChild(c))})};k.prototype.runScripts=function(a){function b(e){if(e<d){var f=
c[e],h=document.createElement("script");f.removeAttribute("import-dependency");l(f.attributes,function(a){return h.setAttribute(a.name,a.value)});p=h;f.parentNode.replaceChild(h,f);g(h,function(){p=null;b(e+1)})}else a()}var c=document.querySelectorAll("script[import-dependency]"),d=c.length;b(0)};k.prototype.waitForStyles=function(a){var b=document.querySelectorAll("style[import-dependency],\n    link[rel=stylesheet][import-dependency]"),d=b.length;if(d){var e=x&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");
l(b,function(b){g(b,function(){b.removeAttribute("import-dependency");0===--d&&a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=c(b);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};k.prototype.fireEvents=function(){var a=this,b=document.querySelectorAll("link[rel=import]");
l(b,function(b){return a.fireEventIfNeeded(b)},!0)};k.prototype.fireEventIfNeeded=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState="complete"),a.dispatchEvent(b(a.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};k.prototype.handleMutations=function(a){var b=this;l(a,function(a){return l(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(h(a)?b.loadImport(a):b.loadImports(a))})})};if(n){var w=document.querySelectorAll("link[rel=import]");l(w,function(a){a.import&&
"loading"===a.import.readyState||(a.__loaded=!0)});w=function(a){a=a.target;h(a)&&(a.__loaded=!0)};document.addEventListener("load",w,!0);document.addEventListener("error",w,!0)}else{var u=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!u||u.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=h(this)?this:c(this);return a?a.href:u&&u.get?u.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});e(function(){return new k})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",
{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=n;a.whenReady=f;a.importForElement=c})(window.HTMLImports=window.HTMLImports||{});window.WebComponents=window.WebComponents||{flags:{}};var ld=document.querySelector('script[src*="webcomponents-lite.js"]'),Ge=/wc-(.+)/,E={};if(!E.noOpts){location.search.slice(1).split("&").forEach(function(a){a=a.split("=");var b;a[0]&&(b=a[0].match(Ge))&&(E[b[1]]=a[1]||!0)});if(ld)for(var md=0,Ba;Ba=ld.attributes[md];md++)"src"!==Ba.name&&(E[Ba.name]=Ba.value||
!0);if(E.log&&E.log.split){var He=E.log.split(",");E.log={};He.forEach(function(a){E.log[a]=!0})}else E.log={}}window.WebComponents.flags=E;var nd=E.shadydom;nd&&(window.ShadyDOM=window.ShadyDOM||{},window.ShadyDOM.force=nd);var od=E.register||E.ce;od&&window.customElements&&(window.customElements.forcePolyfill=od);var D=window.ShadyDOM||{};D.hasNativeShadowDOM=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var zb=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");D.hasDescriptors=
!!(zb&&zb.configurable&&zb.get);D.inUse=D.force||!D.hasNativeShadowDOM;var da=Element.prototype,pd=da.matches||da.matchesSelector||da.mozMatchesSelector||da.msMatchesSelector||da.oMatchesSelector||da.webkitMatchesSelector,gb=document.createTextNode(""),jc=0,fb=[];(new MutationObserver(function(){for(;fb.length;)try{fb.shift()()}catch(a){throw gb.textContent=jc++,a;}})).observe(gb,{characterData:!0});var ja=[],hb;va.list=ja;ta.prototype.schedule=function(){var a=this;this._scheduled||(this._scheduled=
!0,ic(function(){a.flush()}))};ta.prototype.flush=function(){if(this._scheduled){this._scheduled=!1;var a=this.takeRecords();a.length&&this.callbacks.forEach(function(b){b(a)})}};ta.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};var Ac=Element.prototype.appendChild,ob=Element.prototype.insertBefore,ka=Element.prototype.removeChild,Ic=
Element.prototype.setAttribute,qd=Element.prototype.removeAttribute,Ab=Element.prototype.cloneNode,pb=Document.prototype.importNode,Qc=Element.prototype.addEventListener,Tc=Element.prototype.removeEventListener,Pc=Window.prototype.addEventListener,Sc=Window.prototype.removeEventListener,Bb=Element.prototype.dispatchEvent,Ie=Object.freeze({appendChild:Ac,insertBefore:ob,removeChild:ka,setAttribute:Ic,removeAttribute:qd,cloneNode:Ab,importNode:pb,addEventListener:Qc,removeEventListener:Tc,windowAddEventListener:Pc,
windowRemoveEventListener:Sc,dispatchEvent:Bb,querySelector:Element.prototype.querySelector,querySelectorAll:Element.prototype.querySelectorAll}),le=/[&\u00A0"]/g,oe=/[&\u00A0<>]/g,me=mc("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),ne=mc("style script xmp iframe noembed noframes plaintext noscript".split(" ")),B=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),C=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),
Je=Object.freeze({parentNode:aa,firstChild:Ua,lastChild:Va,previousSibling:nc,nextSibling:oc,childNodes:U,parentElement:pc,firstElementChild:qc,lastElementChild:rc,previousElementSibling:sc,nextElementSibling:tc,children:uc,innerHTML:vc,textContent:wc}),Cb=Object.getOwnPropertyDescriptor(Element.prototype,"innerHTML")||Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML"),Ca=document.implementation.createHTMLDocument("inert").createElement("div"),Db=Object.getOwnPropertyDescriptor(Document.prototype,
"activeElement"),xc={parentElement:{get:function(){var a=this.__shady&&this.__shady.parentNode;a&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:pc(this)},configurable:!0},parentNode:{get:function(){var a=this.__shady&&this.__shady.parentNode;return void 0!==a?a:aa(this)},configurable:!0},nextSibling:{get:function(){var a=this.__shady&&this.__shady.nextSibling;return void 0!==a?a:oc(this)},configurable:!0},previousSibling:{get:function(){var a=this.__shady&&this.__shady.previousSibling;
return void 0!==a?a:nc(this)},configurable:!0},className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0},nextElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.nextSibling){for(var a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return tc(this)},configurable:!0},previousElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.previousSibling){for(var a=this.previousSibling;a&&
a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return sc(this)},configurable:!0}},jb={childNodes:{get:function(){if(Z(this)){if(!this.__shady.childNodes){this.__shady.childNodes=[];for(var a=this.firstChild;a;a=a.nextSibling)this.__shady.childNodes.push(a)}var b=this.__shady.childNodes}else b=U(this);b.item=function(a){return b[a]};return b},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=this.__shady&&
this.__shady.firstChild;return void 0!==a?a:Ua(this)},configurable:!0},lastChild:{get:function(){var a=this.__shady&&this.__shady.lastChild;return void 0!==a?a:Va(this)},configurable:!0},textContent:{get:function(){if(Z(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.textContent);return a.join("")}return wc(this)},set:function(a){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(;this.firstChild;)this.removeChild(this.firstChild);
(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.firstChild){for(var a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return qc(this)},configurable:!0},lastElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.lastChild){for(var a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;
return a}return rc(this)},configurable:!0},children:{get:function(){var a=Z(this)?Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE}):uc(this);a.item=function(b){return a[b]};return a},configurable:!0},innerHTML:{get:function(){var a="template"===this.localName?this.content:this;return Z(this)?ib(a):vc(a)},set:function(a){for(var b="template"===this.localName?this.content:this;b.firstChild;)b.removeChild(b.firstChild);for(Cb&&Cb.set?Cb.set.call(Ca,a):Ca.innerHTML=
a;Ca.firstChild;)b.appendChild(Ca.firstChild)},configurable:!0}},rd={shadowRoot:{get:function(){return this.__shady&&this.__shady.publicRoot||null},configurable:!0}},kb={activeElement:{get:function(){var a=Db&&Db.get?Db.get.call(document):D.hasDescriptors?void 0:document.activeElement;if(a&&a.nodeType){var b=!!H(this);if(this===document||b&&this.host!==a&&this.host.contains(a)){for(b=ia(a);b&&b!==this;)a=b.host,b=ia(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},
configurable:!0}},$b=D.hasDescriptors?function(){}:function(a){a.__shady&&a.__shady.__outsideAccessors||(a.__shady=a.__shady||{},a.__shady.__outsideAccessors=!0,L(a,xc,!0))},Zb=D.hasDescriptors?function(){}:function(a){a.__shady&&a.__shady.__insideAccessors||(a.__shady=a.__shady||{},a.__shady.__insideAccessors=!0,L(a,jb,!0),L(a,rd,!0))},xa=null,Ke={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,
wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},Uc={get composed(){!1!==this.isTrusted&&
void 0===this.__composed&&(this.__composed=Ke[this.type]);return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=qb(this.__target,this.composed));return this.__composedPath},get target(){return Kc(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||(this.__relatedTargetComposedPath=qb(this.__relatedTarget,!0));return Kc(this.currentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);
this.__propagationStopped=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.__propagationStopped=this.__immediatePropagationStopped=!0}},sb={focus:!0,blur:!0},Le=rb(window.Event),Me=rb(window.CustomEvent),Ne=rb(window.MouseEvent),Yb={};l.prototype=Object.create(DocumentFragment.prototype);l.prototype._init=function(a,b){this.__localName="ShadyRoot";sa(a);sa(this);this.host=a;this._mode=b&&b.mode;a.__shady=a.__shady||{};a.__shady.root=this;a.__shady.publicRoot=
"closed"!==this._mode?this:null;this._hasRendered=this._renderPending=!1;this._slotList=[];this._slotMap=null;b=U(a);for(var c=0,d=b.length;c<d;c++)ka.call(a,b[c])};l.prototype._asyncRender=function(){var a=this;this._renderPending||(this._renderPending=!0,kc(function(){return a._render()}))};l.prototype._getRenderRoot=function(){for(var a=this,b=this;b;)b._renderPending&&(a=b),b=b._rendererForHost();return a};l.prototype._rendererForHost=function(){var a=this.host.getRootNode();if(H(a))for(var b=
this.host.childNodes,c=0,d;c<b.length;c++)if(d=b[c],this._isInsertionPoint(d))return a};l.prototype._render=function(){this._renderPending&&this._getRenderRoot()._renderRoot()};l.prototype._renderRoot=function(){this._renderPending=!1;this._distribute();this._compose();this._hasRendered=!0};l.prototype._distribute=function(){for(var a=0,b;a<this._slotList.length;a++)b=this._slotList[a],this._clearSlotAssignedNodes(b);for(b=this.host.firstChild;b;b=b.nextSibling)this._distributeNodeToSlot(b);for(a=
0;a<this._slotList.length;a++){b=this._slotList[a];if(!b.__shady.assignedNodes.length)for(var c=b.firstChild;c;c=c.nextSibling)this._distributeNodeToSlot(c,b);c=b.parentNode;(c=c.__shady&&c.__shady.root)&&c._hasInsertionPoint()&&c._renderRoot();this._addAssignedToFlattenedNodes(b.__shady.flattenedNodes,b.__shady.assignedNodes);if(c=b.__shady._previouslyAssignedNodes){for(var d=0;d<c.length;d++)c[d].__shady._prevAssignedSlot=null;b.__shady._previouslyAssignedNodes=null;c.length>b.__shady.assignedNodes.length&&
(b.__shady.dirty=!0)}b.__shady.dirty&&(b.__shady.dirty=!1,this._fireSlotChange(b))}};l.prototype._distributeNodeToSlot=function(a,b){a.__shady=a.__shady||{};var c=a.__shady._prevAssignedSlot;a.__shady._prevAssignedSlot=null;b||(b=(b=this._slotMap[a.slot||"__catchall"])&&b[0]);b?(b.__shady.assignedNodes.push(a),a.__shady.assignedSlot=b):a.__shady.assignedSlot=void 0;c!==a.__shady.assignedSlot&&a.__shady.assignedSlot&&(a.__shady.assignedSlot.__shady.dirty=!0)};l.prototype._clearSlotAssignedNodes=function(a){var b=
a.__shady.assignedNodes;a.__shady.assignedNodes=[];a.__shady.flattenedNodes=[];if(a.__shady._previouslyAssignedNodes=b)for(var c=0;c<b.length;c++){var d=b[c];d.__shady._prevAssignedSlot=d.__shady.assignedSlot;d.__shady.assignedSlot===a&&(d.__shady.assignedSlot=null)}};l.prototype._addAssignedToFlattenedNodes=function(a,b){for(var c=0,d;c<b.length&&(d=b[c]);c++)"slot"==d.localName?this._addAssignedToFlattenedNodes(a,d.__shady.assignedNodes):a.push(b[c])};l.prototype._fireSlotChange=function(a){Bb.call(a,
new Event("slotchange"));a.__shady.assignedSlot&&this._fireSlotChange(a.__shady.assignedSlot)};l.prototype._compose=function(){for(var a=this._slotList,b=[],c=0;c<a.length;c++){var d=a[c].parentNode;d.__shady&&d.__shady.root||!(0>b.indexOf(d))||b.push(d)}for(a=0;a<b.length;a++)c=b[a],this._updateChildNodes(c===this?this.host:c,this._composeNode(c))};l.prototype._composeNode=function(a){var b=[];a=a.childNodes;for(var c=0;c<a.length;c++){var d=a[c];if(this._isInsertionPoint(d)){d=d.__shady.flattenedNodes;
for(var e=0;e<d.length;e++)b.push(d[e])}else b.push(d)}return b};l.prototype._isInsertionPoint=function(a){return"slot"==a.localName};l.prototype._updateChildNodes=function(a,b){for(var c=U(a),d=re(b,0,b.length,c,0,c.length),e=0,f=0,g;e<d.length&&(g=d[e]);e++){for(var h=0,k;h<g.removed.length&&(k=g.removed[h]);h++)aa(k)===a&&ka.call(a,k),c.splice(g.index+f,1);f-=g.addedCount}for(e=0;e<d.length&&(g=d[e]);e++)for(f=c[g.index],h=g.index;h<g.index+g.addedCount;h++)k=b[h],ob.call(a,k,f),c.splice(h,0,k)};
l.prototype._addSlots=function(a){this._slotMap=this._slotMap||{};this._slotList=this._slotList||[];for(var b=0;b<a.length;b++){var c=a[b];c.__shady=c.__shady||{};sa(c);sa(c.parentNode);var d=this._nameForSlot(c);if(this._slotMap[d]){var e=e||{};e[d]=!0;this._slotMap[d].push(c)}else this._slotMap[d]=[c];this._slotList.push(c)}if(e)for(var f in e)this._slotMap[f]=this._sortSlots(this._slotMap[f])};l.prototype._nameForSlot=function(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.__slotName=
b};l.prototype._sortSlots=function(a){return a.sort(function(a,c){a=Vc(a);for(var b=Vc(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})};l.prototype._removeContainedSlots=function(a){this._slotMap=this._slotMap||{};this._slotList=this._slotList||[];var b=this._slotMap,c;for(c in b)for(var d=b[c],e=0;e<d.length;e++){var f=d[e],g;a:{for(g=f;g;){if(g==a){g=!0;break a}g=g.parentNode}g=void 0}if(g){d.splice(e,1);var h=this._slotList.indexOf(f);
0<=h&&this._slotList.splice(h,1);e--;this._removeFlattenedNodes(f);h=!0}}return h};l.prototype._updateSlotName=function(a){var b=a.__slotName,c=this._nameForSlot(a);if(c!==b){b=this._slotMap[b];var d=b.indexOf(a);0<=d&&b.splice(d,1);b=this._slotMap[c]||(this._slotMap[c]=[]);b.push(a);1<b.length&&(this._slotMap[c]=this._sortSlots(b))}};l.prototype._removeFlattenedNodes=function(a){if(a=a.__shady.flattenedNodes)for(var b=0;b<a.length;b++){var c=a[b],d=aa(c);d&&ka.call(d,c)}};l.prototype._hasInsertionPoint=
function(){return!!this._slotList.length};l.prototype.addEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.__shadyTarget=this;this.host.addEventListener(a,b,c)};l.prototype.removeEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.__shadyTarget=this;this.host.removeEventListener(a,b,c)};l.prototype.getElementById=function(a){return wa(this,function(b){return b.id==a},function(a){return!!a})[0]||null};(function(a){L(a,jb,!0);L(a,kb,!0)})(l.prototype);var ve=
{addEventListener:Nc.bind(window),removeEventListener:Rc.bind(window)},ue={addEventListener:Nc,removeEventListener:Rc,appendChild:function(a){return lb(this,a)},insertBefore:function(a,b){return lb(this,a,b)},removeChild:function(a){return mb(this,a)},replaceChild:function(a,b){lb(this,a,b);mb(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=Ab.call(this,a);else if(b=Ab.call(this,!1),a){a=this.childNodes;for(var c=0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},
getRootNode:function(a){return Ec(this,a)},get isConnected(){var a=this.ownerDocument;if(a&&a.contains&&a.contains(this)||(a=a.documentElement)&&a.contains&&a.contains(this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(a instanceof l?a.host:void 0);return!!(a&&a instanceof Document)},dispatchEvent:function(a){va();return Bb.call(this,a)}},we={get assignedSlot(){return Wc(this)}},tb={querySelector:function(a){return wa(this,function(b){return pd.call(b,a)},function(a){return!!a})[0]||
null},querySelectorAll:function(a){return wa(this,function(b){return pd.call(b,a)})}},Zc={assignedNodes:function(a){if("slot"===this.localName)return Gc(this),this.__shady?(a&&a.flatten?this.__shady.flattenedNodes:this.__shady.assignedNodes)||[]:[]}},Xc=eb({setAttribute:function(a,b){Hc(this,a,b)},removeAttribute:function(a){qd.call(this,a);Dc(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new l(Yb,this,a)},get slot(){return this.getAttribute("slot")},
set slot(a){Hc(this,"slot",a)},get assignedSlot(){return Wc(this)}},tb,Zc);Object.defineProperties(Xc,rd);var Yc=eb({importNode:function(a,b){return Jc(a,b)},getElementById:function(a){return wa(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},tb);Object.defineProperties(Yc,{_activeElement:kb.activeElement});var Oe=HTMLElement.prototype.blur,xe=eb({blur:function(){var a=this.__shady&&this.__shady.root;(a=a&&a.activeElement)?a.blur():Oe.call(this)}});D.inUse&&(window.ShadyDOM={inUse:D.inUse,
patch:function(a){return a},isShadyRoot:H,enqueue:kc,flush:va,settings:D,filterMutations:ke,observeChildren:Yd,unobserveChildren:Xd,nativeMethods:Ie,nativeTree:Je},window.Event=Le,window.CustomEvent=Me,window.MouseEvent=Ne,qe(),te(),window.ShadowRoot=l);var ye=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));u.prototype.setDefinition=function(a,b){this._localNameToDefinition.set(a,b);this._constructorToDefinition.set(b.constructor,
b)};u.prototype.localNameToDefinition=function(a){return this._localNameToDefinition.get(a)};u.prototype.constructorToDefinition=function(a){return this._constructorToDefinition.get(a)};u.prototype.addPatch=function(a){this._hasPatches=!0;this._patches.push(a)};u.prototype.patchTree=function(a){var b=this;this._hasPatches&&P(a,function(a){return b.patch(a)})};u.prototype.patch=function(a){if(this._hasPatches&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this._patches.length;b++)this._patches[b](a)}};
u.prototype.connectTree=function(a){var b=[];P(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=b[a];1===c.__CE_state?this.connectedCallback(c):this.upgradeElement(c)}};u.prototype.disconnectTree=function(a){var b=[];P(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=b[a];1===c.__CE_state&&this.disconnectedCallback(c)}};u.prototype.patchAndUpgradeTree=function(a,b){var c=this;b=void 0===b?new Set:b;var d=[];P(a,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var e=
a.import;e instanceof Node&&"complete"===e.readyState?(e.__CE_isImportDocument=!0,e.__CE_hasRegistry=!0):a.addEventListener("load",function(){var d=a.import;d.__CE_documentLoadHandled||(d.__CE_documentLoadHandled=!0,d.__CE_isImportDocument=!0,d.__CE_hasRegistry=!0,new Set(b),b.delete(d),c.patchAndUpgradeTree(d,b))})}else d.push(a)},b);if(this._hasPatches)for(a=0;a<d.length;a++)this.patch(d[a]);for(a=0;a<d.length;a++)this.upgradeElement(d[a])};u.prototype.upgradeElement=function(a){if(void 0===a.__CE_state){var b=
this.localNameToDefinition(a.localName);if(b){b.constructionStack.push(a);var c=b.constructor;try{try{if(new c!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{b.constructionStack.pop()}}catch(f){throw a.__CE_state=2,f;}a.__CE_state=1;a.__CE_definition=b;if(b.attributeChangedCallback)for(b=b.observedAttributes,c=0;c<b.length;c++){var d=b[c],e=a.getAttribute(d);null!==e&&this.attributeChangedCallback(a,d,null,e,null)}n(a)&&this.connectedCallback(a)}}};
u.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};u.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};u.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};Sa.prototype.disconnect=function(){this._observer&&this._observer.disconnect()};
Sa.prototype._handleMutations=function(a){var b=this._document.readyState;"interactive"!==b&&"complete"!==b||this.disconnect();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)this._internals.patchAndUpgradeTree(c[d])};Ta.prototype.resolve=function(a){if(this._value)throw Error("Already resolved.");this._value=a;this._resolve&&this._resolve(a)};Ta.prototype.toPromise=function(){return this._promise};z.prototype.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");
if(!$c(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this._internals.localNameToDefinition(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this._elementDefinitionIsRunning)throw Error("A custom element is already being defined.");this._elementDefinitionIsRunning=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");
var f=d("connectedCallback");var g=d("disconnectedCallback");var h=d("adoptedCallback");var k=d("attributeChangedCallback");var l=b.observedAttributes||[]}catch(La){return}finally{this._elementDefinitionIsRunning=!1}this._internals.setDefinition(a,{localName:a,constructor:b,connectedCallback:f,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]});this._unflushedLocalNames.push(a);this._flushPending||(this._flushPending=!0,this._flushCallback(function(){return c._flush()}))};
z.prototype._flush=function(){if(!1!==this._flushPending)for(this._flushPending=!1,this._internals.patchAndUpgradeTree(document);0<this._unflushedLocalNames.length;){var a=this._unflushedLocalNames.shift();(a=this._whenDefinedDeferred.get(a))&&a.resolve(void 0)}};z.prototype.get=function(a){if(a=this._internals.localNameToDefinition(a))return a.constructor};z.prototype.whenDefined=function(a){if(!$c(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this._whenDefinedDeferred.get(a);
if(b)return b.toPromise();b=new Ta;this._whenDefinedDeferred.set(a,b);this._internals.localNameToDefinition(a)&&-1===this._unflushedLocalNames.indexOf(a)&&b.resolve(void 0);return b.toPromise()};z.prototype.polyfillWrapFlushCallback=function(a){this._documentConstructionObserver.disconnect();var b=this._flushCallback;this._flushCallback=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=z;z.prototype.define=z.prototype.define;z.prototype.get=z.prototype.get;z.prototype.whenDefined=
z.prototype.whenDefined;z.prototype.polyfillWrapFlushCallback=z.prototype.polyfillWrapFlushCallback;var Oa=window.Document.prototype.createElement,Sd=window.Document.prototype.createElementNS,Rd=window.Document.prototype.importNode,Td=window.Document.prototype.prepend,Ud=window.Document.prototype.append,Nb=window.Node.prototype.cloneNode,qa=window.Node.prototype.appendChild,Vb=window.Node.prototype.insertBefore,Pa=window.Node.prototype.removeChild,Wb=window.Node.prototype.replaceChild,Ra=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),Mb=window.Element.prototype.attachShadow,Ma=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),Qa=window.Element.prototype.getAttribute,Ob=window.Element.prototype.setAttribute,Qb=window.Element.prototype.removeAttribute,ra=window.Element.prototype.getAttributeNS,Pb=window.Element.prototype.setAttributeNS,Rb=window.Element.prototype.removeAttributeNS,Tb=window.Element.prototype.insertAdjacentElement,Id=window.Element.prototype.prepend,Jd=window.Element.prototype.append,
Ld=window.Element.prototype.before,Md=window.Element.prototype.after,Nd=window.Element.prototype.replaceWith,Od=window.Element.prototype.remove,Wd=window.HTMLElement,Na=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Sb=window.HTMLElement.prototype.insertAdjacentElement,Xb=new function(){},Da=window.customElements;if(!Da||Da.forcePolyfill||"function"!=typeof Da.define||"function"!=typeof Da.get){var ma=new u;Vd(ma);Qd(ma);Pd(ma);Hd(ma);document.__CE_hasRegistry=!0;var Pe=
new z(ma);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:Pe})}var K={STYLE_RULE:1,KEYFRAMES_RULE:7,MEDIA_RULE:4,MIXIN_RULE:1E3},G={comments:/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,port:/@import[^;]*;/gim,customProp:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,mixinProp:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,mixinApply:/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,varApply:/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,keyframesRule:/^@[^\s]*keyframes/,
multipleSpaces:/\s+/g},y=!(window.ShadyDOM&&window.ShadyDOM.inUse);if(window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss)var x=window.ShadyCSS.nativeCss;else window.ShadyCSS?(cd(window.ShadyCSS),window.ShadyCSS=void 0):cd(window.WebComponents&&window.WebComponents.flags);var Ea=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,Fa=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Qe=/(--[\w-]+)\s*([:,;)]|$)/gi,Re=/(animation\s*:)|(animation-name\s*:)/,
Ae=/@media\s(.*)/,Se=/\{[^}]*\}/g,S=null;r.prototype.dom=function(a,b,c){a.__styleScoped?a.__styleScoped=null:this._transformDom(a,b||"",c)};r.prototype._transformDom=function(a,b,c){a.nodeType===Node.ELEMENT_NODE&&this.element(a,b,c);if(a="template"===a.localName?(a.content||a._content).childNodes:a.children||a.childNodes)for(var d=0;d<a.length;d++)this._transformDom(a[d],b,c)};r.prototype.element=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),
a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(Te);c?d&&(b=d.replace("style-scope","").replace(b,""),za(a,b)):za(a,(d?d+" ":"")+"style-scope "+b)}};r.prototype.elementStyles=function(a,b,c){var d=a.__cssBuild;y||"shady"===d?b=ba(b,c):(a=T(a),b=this.css(b,a.is,a.typeExtension,c)+"\n\n");return b.trim()};r.prototype.css=function(a,b,c,d){var e=this._calcHostScope(b,c);b=this._calcElementScope(b);var f=this;return ba(a,function(a){a.isScoped||(f.rule(a,b,e),a.isScoped=!0);d&&d(a,b,
e)})};r.prototype._calcElementScope=function(a){return a?Ue+a:""};r.prototype._calcHostScope=function(a,b){return b?"[is="+a+"]":a};r.prototype.rule=function(a,b,c){this._transformRule(a,this._transformComplexSelector,b,c)};r.prototype._transformRule=function(a,b,c,d){a.selector=a.transformedSelector=this._transformRuleCss(a,b,c,d)};r.prototype._transformRuleCss=function(a,b,c,d){var e=a.selector.split(sd);if(!dd(a)){a=0;for(var f=e.length,g;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.join(sd)};
r.prototype._twiddleNthPlus=function(a){return a.replace(Eb,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})};r.prototype._transformComplexSelector=function(a,b,c){var d=this,e=!1;a=a.trim();var f=Eb.test(a);f&&(a=a.replace(Eb,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=this._twiddleNthPlus(a));a=a.replace(Ve,Fb+" $1");a=a.replace(We,function(a,f,k){e||(a=d._transformCompoundSelector(k,f,b,c),e=e||a.stop,
f=a.combinator,k=a.value);return f+k});f&&(a=this._twiddleNthPlus(a));return a};r.prototype._transformCompoundSelector=function(a,b,c,d){var e=a.indexOf(Gb);0<=a.indexOf(Fb)?a=this._transformHostSelector(a,d):0!==e&&(a=c?this._transformSimpleSelector(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Xe,function(a,b){return" > "+b}))}a=a.replace(Ye,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,combinator:b,stop:f}};r.prototype._transformSimpleSelector=
function(a,b){a=a.split(td);a[0]+=b;return a.join(td)};r.prototype._transformHostSelector=function(a,b){var c=a.match(ud);return(c=c&&c[2].trim()||"")?c[0].match(vd)?a.replace(ud,function(a,c,f){return b+f}):c.split(vd)[0]===b?c:Ze:a.replace(Fb,b)};r.prototype.documentRule=function(a){a.selector=a.parsedSelector;this.normalizeRootSelector(a);this._transformRule(a,this._transformDocumentSelector)};r.prototype.normalizeRootSelector=function(a){a.selector===$e&&(a.selector="html")};r.prototype._transformDocumentSelector=
function(a){return a.match(Gb)?this._transformComplexSelector(a,wd):this._transformSimpleSelector(a.trim(),wd)};O.global.Object.defineProperties(r.prototype,{SCOPE_NAME:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});var Eb=/:(nth[-\w]+)\(([^)]+)\)/,wd=":not(.style-scope)",sd=",",We=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,vd=/[[.:#*]/,Fb=":host",$e=":root",Gb="::slotted",Ve=new RegExp("^("+Gb+")"),ud=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Xe=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,
Ye=/(.*):dir\((?:(ltr|rtl))\)/,Ue=".",td=":",Te="class",Ze="should_not_match",v=new r;t.get=function(a){return a?a.__styleInfo:null};t.set=function(a,b){return a.__styleInfo=b};t.prototype._getStyleRules=function(){return this.styleRules};t.prototype._getStyleRules=t.prototype._getStyleRules;var xd=function(a){return a.matches||a.matchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector||a.webkitMatchesSelector}(window.Element.prototype),af=navigator.userAgent.match("Trident");
p.prototype.decorateStyles=function(a){var b=this,c={},d=[],e=0;ca(a,function(a){b.decorateRule(a);a.index=e++;b.collectPropertiesInCssText(a.propertyInfo.cssText,c)},function(a){d.push(a)});a._keyframes=d;a=[];for(var f in c)a.push(f);return a};p.prototype.decorateRule=function(a){if(a.propertyInfo)return a.propertyInfo;var b={},c={};this.collectProperties(a,c)&&(b.properties=c,a.rules=null);b.cssText=this.collectCssText(a);return a.propertyInfo=b};p.prototype.collectProperties=function(a,b){var c=
a.propertyInfo;if(c){if(c.properties)return Object.assign(b,c.properties),!0}else{c=a.parsedCssText;for(var d;a=Ea.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}};p.prototype.collectCssText=function(a){return this.collectConsumingCssText(a.parsedCssText)};p.prototype.collectConsumingCssText=function(a){return a.replace(Se,"").replace(Ea,"")};p.prototype.collectPropertiesInCssText=function(a,b){for(var c;c=Qe.exec(a);){var d=c[1];":"!==c[2]&&(b[d]=!0)}};
p.prototype.reify=function(a){for(var b=Object.getOwnPropertyNames(a),c=0,d;c<b.length;c++)d=b[c],a[d]=this.valueForProperty(a[d],a)};p.prototype.valueForProperty=function(a,b){if(a)if(0<=a.indexOf(";"))a=this.valueForProperties(a,b);else{var c=this;a=fd(a,function(a,e,f,g){if(!e)return a+g;(e=c.valueForProperty(b[e],b))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=c.valueForProperty(b[f]||f,b)||f;return a+(e||"")+g})}return a&&a.trim()||""};p.prototype.valueForProperties=function(a,b){a=
a.split(";");for(var c=0,d,e;c<a.length;c++)if(d=a[c]){Fa.lastIndex=0;if(e=Fa.exec(d))d=this.valueForProperty(b[e[1]],b);else if(e=d.indexOf(":"),-1!==e){var f=d.substring(e);f=f.trim();f=this.valueForProperty(f,b)||f;d=d.substring(0,e)+f}a[c]=d&&d.lastIndexOf(";")===d.length-1?d.slice(0,-1):d||""}return a.join(";")};p.prototype.applyProperties=function(a,b){var c="";a.propertyInfo||this.decorateRule(a);a.propertyInfo.cssText&&(c=this.valueForProperties(a.propertyInfo.cssText,b));a.cssText=c};p.prototype.applyKeyframeTransforms=
function(a,b){var c=a.cssText,d=a.cssText;null==a.hasAnimations&&(a.hasAnimations=Re.test(c));if(a.hasAnimations)if(null==a.keyframeNamesToTransform){a.keyframeNamesToTransform=[];for(var e in b)d=b[e],d=d(c),c!==d&&(c=d,a.keyframeNamesToTransform.push(e))}else{for(e=0;e<a.keyframeNamesToTransform.length;++e)d=b[a.keyframeNamesToTransform[e]],c=d(c);d=c}a.cssText=d};p.prototype.propertyDataFromStyles=function(a,b){var c={},d=this,e=[];ca(a,function(a){a.propertyInfo||d.decorateRule(a);var f=a.transformedSelector||
a.parsedSelector;b&&a.propertyInfo.properties&&f&&xd.call(b,f)&&(d.collectProperties(a,c),a=a.index,f=parseInt(a/32,10),e[f]=(e[f]||0)|1<<a%32)},null,!0);return{properties:c,key:e}};p.prototype.whenHostOrRootRule=function(a,b,c,d){b.propertyInfo||this.decorateRule(b);if(b.propertyInfo.properties){var e=T(a);a=e.is;e=e.typeExtension;e=a?v._calcHostScope(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),
h=!g&&0===f.indexOf(e));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=e,h&&(y&&!b.transformedSelector&&(b.transformedSelector=v._transformRuleCss(b,v._transformComplexSelector,v._calcElementScope(a),e)),c=b.transformedSelector||e),d({selector:c,isHost:h,isRoot:g})}};p.prototype.hostAndRootPropertiesForScope=function(a,b){var c={},d={},e=this,f=b&&b.__cssBuild;ca(b,function(b){e.whenHostOrRootRule(a,b,f,function(f){xd.call(a._element||a,f.selector)&&(f.isHost?e.collectProperties(b,
c):e.collectProperties(b,d))})},null,!0);return{rootProps:d,hostProps:c}};p.prototype.transformStyles=function(a,b,c){var d=this,e=T(a),f=v._calcHostScope(e.is,e.typeExtension);e=a.extends?"\\"+f.slice(0,-1)+"\\]":f;var g=new RegExp("(?:^|[^.#[:])"+e+"($|[.:[\\s>+~])");e=t.get(a).styleRules;var h=this._elementKeyframeTransforms(a,e,c);return v.elementStyles(a,e,function(a){d.applyProperties(a,b);y||dd(a)||!a.cssText||(d.applyKeyframeTransforms(a,h),d._scopeSelector(a,g,f,c))})};p.prototype._elementKeyframeTransforms=
function(a,b,c){a=b._keyframes;b={};if(!y&&a)for(var d=0,e=a[d];d<a.length;e=a[++d])this._scopeKeyframes(e,c),b[e.keyframesName]=this._keyframesRuleTransformer(e);return b};p.prototype._keyframesRuleTransformer=function(a){return function(b){return b.replace(a.keyframesNameRx,a.transformedKeyframesName)}};p.prototype._scopeKeyframes=function(a,b){a.keyframesNameRx=new RegExp(a.keyframesName,"g");a.transformedKeyframesName=a.keyframesName+"-"+b;a.transformedSelector=a.transformedSelector||a.selector;
a.selector=a.transformedSelector.replace(a.keyframesName,a.transformedKeyframesName)};p.prototype._scopeSelector=function(a,b,c,d){a.transformedSelector=a.transformedSelector||a.selector;d="."+d;for(var e=a.transformedSelector.split(","),f=0,g=e.length,h;f<g&&(h=e[f]);f++)e[f]=h.match(b)?h.replace(c,d):d+" "+h;a.selector=e.join(",")};p.prototype.applyElementScopeSelector=function(a,b,c){var d=a.getAttribute("class")||"",e=d;c&&(e=d.replace(new RegExp("\\s*x-scope\\s*"+c+"\\s*","g")," "));e+=(e?" ":
"")+"x-scope "+b;d!==e&&za(a,e)};p.prototype.applyElementStyle=function(a,b,c,d){b=d?d.textContent||"":this.transformStyles(a,b,c);var e=t.get(a),f=e.customStyle;f&&!y&&f!==d&&(f._useCount--,0>=f._useCount&&f.parentNode&&f.parentNode.removeChild(f));y?e.customStyle?(e.customStyle.textContent=b,d=e.customStyle):b&&(d=wb(b,c,a.shadowRoot,e.placeholder)):d?d.parentNode||(af&&-1<b.indexOf("@media")&&(d.textContent=b),ed(d,null,e.placeholder)):b&&(d=wb(b,c,null,e.placeholder));d&&(d._useCount=d._useCount||
0,e.customStyle!=d&&d._useCount++,e.customStyle=d);return d};p.prototype.applyCustomStyle=function(a,b){var c=ya(a),d=this;a.textContent=ba(c,function(a){var c=a.cssText=a.parsedCssText;a.propertyInfo&&a.propertyInfo.cssText&&(c=c.replace(G.customProp,"").replace(G.mixinProp,""),a.cssText=d.valueForProperties(c,b))})};O.global.Object.defineProperties(p.prototype,{XSCOPE_NAME:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var N=new p,Hb={},Ga=window.customElements;if(Ga&&!y){var bf=
Ga.define;Ga.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+" "),e=document.head;e.insertBefore(d,(S?S.nextSibling:null)||e.firstChild);S=d;Hb[a]=d;return bf.call(Ga,a,b,c)}}oa.prototype._validate=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.properties[e]!==b[e])return!1}return!0};oa.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({properties:b,styleElement:c,scopeSelector:d});e.length>this.typeMax&&e.shift();this.cache[a]=e};oa.prototype.fetch=
function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this._validate(e,b,c))return e}};if(!y){var yd=new MutationObserver(gd),zd=function(a){yd.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)zd(document);else{var Ib=function(){zd(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Ib):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Ib();document.removeEventListener("readystatechange",
a)};document.addEventListener("readystatechange",a)}else Ib()})}Lb=function(){gd(yd.takeRecords())}}var Aa={},De=Promise.resolve(),xb=null,id=window.HTMLImports&&window.HTMLImports.whenReady||null,yb,Ha=null,na=null;F.prototype.enqueueDocumentValidation=function(){!this.enqueued&&na&&(this.enqueued=!0,Kb(na))};F.prototype.addCustomStyle=function(a){a.__seenByShadyCSS||(a.__seenByShadyCSS=!0,this.customStyles.push(a),this.enqueueDocumentValidation())};F.prototype.getStyleForCustomStyle=function(a){return a.__shadyCSSCachedStyle?
a.__shadyCSSCachedStyle:a.getStyle?a.getStyle():a};F.prototype.processStyles=function(){for(var a=this.customStyles,b=0;b<a.length;b++){var c=a[b];if(!c.__shadyCSSCachedStyle){var d=this.getStyleForCustomStyle(c);d&&(d=d.__appliedElement||d,Ha&&Ha(d),c.__shadyCSSCachedStyle=d)}}return a};F.prototype.addCustomStyle=F.prototype.addCustomStyle;F.prototype.getStyleForCustomStyle=F.prototype.getStyleForCustomStyle;F.prototype.processStyles=F.prototype.processStyles;Object.defineProperties(F.prototype,
{transformCallback:{get:function(){return Ha},set:function(a){Ha=a}},validateCallback:{get:function(){return na},set:function(a){var b=!1;na||(b=!0);na=a;b&&this.enqueueDocumentValidation()}}});var Ad=new oa;k.prototype.flush=function(){Lb()};k.prototype._generateScopeSelector=function(a){var b=this._scopeCounter[a]=(this._scopeCounter[a]||0)+1;return a+"-"+b};k.prototype.getStyleAst=function(a){return ya(a)};k.prototype.styleAstToString=function(a){return ba(a)};k.prototype._gatherStyles=function(a){a=
a.content.querySelectorAll("style");for(var b=[],c=0;c<a.length;c++){var d=a[c];b.push(d.textContent);d.parentNode.removeChild(d)}return b.join("").trim()};k.prototype._getCssBuild=function(a){return(a=a.content.querySelector("style"))?a.getAttribute("css-build")||"":""};k.prototype.prepareTemplate=function(a,b,c){if(!a._prepared){a._prepared=!0;a.name=b;a.extends=c;Aa[b]=a;var d=this._getCssBuild(a),e=this._gatherStyles(a);c={is:b,extends:c,__cssBuild:d};y||v.dom(a.content,b);this._ensure();var f=
Fa.test(e)||Ea.test(e);Fa.lastIndex=0;Ea.lastIndex=0;e=vb(e);f&&x&&this._applyShim&&this._applyShim.transformRules(e,b);a._styleAst=e;a._cssBuild=d;d=[];x||(d=N.decorateStyles(a._styleAst,c));if(!d.length||x)b=this._generateStaticStyle(c,a._styleAst,y?a.content:null,Hb[b]),a._style=b;a._ownPropertyNames=d}};k.prototype._generateStaticStyle=function(a,b,c,d){b=v.elementStyles(a,b);if(b.length)return wb(b,a.is,c,d)};k.prototype._prepareHost=function(a){var b=T(a),c=b.is;b=b.typeExtension;var d=Hb[c],
e=Aa[c];if(e){var f=e._styleAst;var g=e._ownPropertyNames;var h=e._cssBuild}return t.set(a,new t(f,d,g,c,b,h))};k.prototype._ensureApplyShim=function(){!this._applyShim&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(this._applyShim=window.ShadyCSS.ApplyShim,this._applyShim.invalidCallback=Be)};k.prototype._ensureCustomStyleInterface=function(){var a=this;!this._customStyleInterface&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this._customStyleInterface=window.ShadyCSS.CustomStyleInterface,
this._customStyleInterface.transformCallback=function(b){a.transformCustomStyleForDocument(b)},this._customStyleInterface.validateCallback=function(){requestAnimationFrame(function(){(a._customStyleInterface.enqueued||a._elementsHaveApplied)&&a.flushCustomStyles()})})};k.prototype._ensure=function(){this._ensureApplyShim();this._ensureCustomStyleInterface()};k.prototype.flushCustomStyles=function(){this._ensure();if(this._customStyleInterface){var a=this._customStyleInterface.processStyles();this._customStyleInterface.enqueued&&
(x?this._revalidateCustomStyleApplyShim(a):(this._updateProperties(this._documentOwner,this._documentOwnerStyleInfo),this._applyCustomStyles(a)),this._customStyleInterface.enqueued=!1,this._elementsHaveApplied&&!x&&this.styleDocument())}};k.prototype.styleElement=function(a,b){var c=T(a).is,d=t.get(a);d||(d=this._prepareHost(a));this._isRootOwner(a)||(this._elementsHaveApplied=!0);b&&(d.overrideStyleProperties=d.overrideStyleProperties||{},Object.assign(d.overrideStyleProperties,b));if(x){if(d.overrideStyleProperties){b=
d.overrideStyleProperties;for(var e in b)null===e?a.style.removeProperty(e):a.style.setProperty(e,b[e])}if(((e=Aa[c])||this._isRootOwner(a))&&e&&e._style&&!hd(e)){if(hd(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)this._ensure(),this._applyShim&&this._applyShim.transformRules(e._styleAst,c),e._style.textContent=v.elementStyles(a,d.styleRules),Ce(e);y&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=v.elementStyles(a,d.styleRules));d.styleRules=e._styleAst}}else this._updateProperties(a,
d),d.ownStylePropertyNames&&d.ownStylePropertyNames.length&&this._applyStyleProperties(a,d)};k.prototype._styleOwnerForNode=function(a){return(a=a.getRootNode().host)?t.get(a)?a:this._styleOwnerForNode(a):this._documentOwner};k.prototype._isRootOwner=function(a){return a===this._documentOwner};k.prototype._applyStyleProperties=function(a,b){var c=T(a).is,d=Ad.fetch(c,b.styleProperties,b.ownStylePropertyNames),e=d?d.styleElement:null,f=b.scopeSelector;b.scopeSelector=d&&d.scopeSelector||this._generateScopeSelector(c);
e=N.applyElementStyle(a,b.styleProperties,b.scopeSelector,e);y||N.applyElementScopeSelector(a,b.scopeSelector,f);d||Ad.store(c,b.styleProperties,e,b.scopeSelector);return e};k.prototype._updateProperties=function(a,b){var c=this._styleOwnerForNode(a),d=t.get(c);c=Object.create(d.styleProperties||null);var e=N.hostAndRootPropertiesForScope(a,b.styleRules);a=N.propertyDataFromStyles(d.styleRules,a).properties;Object.assign(c,e.hostProps,a,e.rootProps);this._mixinOverrideStyles(c,b.overrideStyleProperties);
N.reify(c);b.styleProperties=c};k.prototype._mixinOverrideStyles=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};k.prototype.styleDocument=function(a){this.styleSubtree(this._documentOwner,a)};k.prototype.styleSubtree=function(a,b){var c=a.shadowRoot;(c||this._isRootOwner(a))&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};k.prototype._revalidateCustomStyleApplyShim=
function(a){for(var b=0;b<a.length;b++){var c=this._customStyleInterface.getStyleForCustomStyle(a[b]);c&&this._revalidateApplyShim(c)}};k.prototype._applyCustomStyles=function(a){for(var b=0;b<a.length;b++){var c=this._customStyleInterface.getStyleForCustomStyle(a[b]);c&&N.applyCustomStyle(c,this._documentOwnerStyleInfo.styleProperties)}};k.prototype.transformCustomStyleForDocument=function(a){var b=this,c=ya(a);ca(c,function(a){y?v.normalizeRootSelector(a):v.documentRule(a);x&&(b._ensure(),b._applyShim&&
b._applyShim.transformRule(a))});x?a.textContent=ba(c):this._documentOwnerStyleInfo.styleRules.rules.push(c)};k.prototype._revalidateApplyShim=function(a){if(x&&this._applyShim){var b=ya(a);this._ensure();this._applyShim.transformRules(b);a.textContent=ba(b)}};k.prototype.getComputedStyleValue=function(a,b){var c;x||(c=(t.get(a)||t.get(this._styleOwnerForNode(a))).styleProperties[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};k.prototype.setElementClass=function(a,b){var c=
a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===v.SCOPE_NAME){c=d[e+1];break}}}c&&b.push(v.SCOPE_NAME,c);x||(c=t.get(a))&&c.scopeSelector&&b.push(N.XSCOPE_NAME,c.scopeSelector);za(a,b.join(" "))};k.prototype._styleInfoForNode=function(a){return t.get(a)};k.prototype.flush=k.prototype.flush;k.prototype.prepareTemplate=k.prototype.prepareTemplate;k.prototype.styleElement=k.prototype.styleElement;
k.prototype.styleDocument=k.prototype.styleDocument;k.prototype.styleSubtree=k.prototype.styleSubtree;k.prototype.getComputedStyleValue=k.prototype.getComputedStyleValue;k.prototype.setElementClass=k.prototype.setElementClass;k.prototype._styleInfoForNode=k.prototype._styleInfoForNode;k.prototype.transformCustomStyleForDocument=k.prototype.transformCustomStyleForDocument;k.prototype.getStyleAst=k.prototype.getStyleAst;k.prototype.styleAstToString=k.prototype.styleAstToString;k.prototype.flushCustomStyles=
k.prototype.flushCustomStyles;Object.defineProperties(k.prototype,{nativeShadow:{get:function(){return y}},nativeCss:{get:function(){return x}}});var I=new k;if(window.ShadyCSS){var Bd=window.ShadyCSS.ApplyShim;var Cd=window.ShadyCSS.CustomStyleInterface}window.ShadyCSS={ScopingShim:I,prepareTemplate:function(a,b,c){I.flushCustomStyles();I.prepareTemplate(a,b,c)},styleSubtree:function(a,b){I.flushCustomStyles();I.styleSubtree(a,b)},styleElement:function(a){I.flushCustomStyles();I.styleElement(a)},
styleDocument:function(a){I.flushCustomStyles();I.styleDocument(a)},getComputedStyleValue:function(a,b){return I.getComputedStyleValue(a,b)},nativeCss:x,nativeShadow:y};Bd&&(window.ShadyCSS.ApplyShim=Bd);Cd&&(window.ShadyCSS.CustomStyleInterface=Cd);var Jb=window.customElements,Ia=window.HTMLImports;window.WebComponents=window.WebComponents||{};if(Jb&&Jb.polyfillWrapFlushCallback){var Ja,Dd=function(){if(Ja){var a=Ja;Ja=null;a();return!0}},Ed=Ia.whenReady;Jb.polyfillWrapFlushCallback(function(a){Ja=
a;Ed(Dd)});Ia.whenReady=function(a){Ed(function(){Dd()?Ia.whenReady(a):a()})}}Ia.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var Fd=document.createElement("style");Fd.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var Gd=document.querySelector("head");Gd.insertBefore(Fd,Gd.firstChild)})();}).call(this);

//# sourceMappingURL=webcomponents-lite.js.map
